//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBTS.EntityFramework.Control
{
    using System;
    
    public partial class AuthenticateUser_Result1
    {
        public string DBINFO { get; set; }
        public string DISPLAY { get; set; }
    }
}
