//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBTS.EntityFramework.Control
{
    using System;
    
    public partial class AuthenticateUser_Result2
    {
        public Nullable<bool> U_SUSPEND { get; set; }
        public System.Guid U_CODE { get; set; }
        public string U_LOGINID { get; set; }
        public string U_NAME { get; set; }
        public string U_DESIGNATION { get; set; }
        public string U_PASSWORD { get; set; }
        public Nullable<System.Guid> U_REPORTINGTO { get; set; }
        public Nullable<System.DateTime> U_DOB { get; set; }
        public string U_DEFAULTLINK { get; set; }
        public string U_EMAIL { get; set; }
        public Nullable<System.DateTime> U_ACTIVETILL { get; set; }
        public string U_AVATAR { get; set; }
        public string U_BU { get; set; }
        public string U_BRANCH { get; set; }
        public string U_WH { get; set; }
        public string U_DEPT { get; set; }
        public string C_ID { get; set; }
        public string C_NAME { get; set; }
        public string C_ADDRESS { get; set; }
        public string C_CITY { get; set; }
        public string C_ZIP { get; set; }
        public string C_STATE { get; set; }
        public string C_COUNTRY { get; set; }
        public string C_TRN_CURRENCY { get; set; }
        public string C_LOGO { get; set; }
        public string C_LOGO_WIDTH { get; set; }
        public string C_LOGO_HEIGHT { get; set; }
        public Nullable<System.DateTime> C_FYEAR_START { get; set; }
        public System.DateTime C_FYEAR_END { get; set; }
        public Nullable<int> C_LONGITUDE { get; set; }
        public Nullable<int> C_LATITUDE { get; set; }
        public string C_SMTPHOST_IN { get; set; }
        public Nullable<int> C_SMTPHOST_IN_PORT { get; set; }
        public string C_SMTPHOST_OUT { get; set; }
        public Nullable<int> C_SMTPHOST_OUT_PORT { get; set; }
        public string C_SMTP_USER { get; set; }
        public string C_SMTP_PASSWORD { get; set; }
        public Nullable<bool> C_SSL_ENABLED { get; set; }
        public string C_DB_SERVER { get; set; }
        public string C_DB_NAME { get; set; }
        public string C_DB_USER { get; set; }
        public string C_DB_PASSWORD { get; set; }
        public System.DateTime C_TODAY { get; set; }
    }
}
