//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBTS.EntityFramework.Control
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ControlEntities : DbContext
    {
        public ControlEntities()
            : base("name=ControlEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int Sp_Key_Fields(string v_table, ObjectParameter v_output)
        {
            var v_tableParameter = v_table != null ?
                new ObjectParameter("v_table", v_table) :
                new ObjectParameter("v_table", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Key_Fields", v_tableParameter, v_output);
        }
    
        public virtual int Usp_Ezy_Tools_BackupAllDatabases(string path, string type)
        {
            var pathParameter = path != null ?
                new ObjectParameter("Path", path) :
                new ObjectParameter("Path", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Usp_Ezy_Tools_BackupAllDatabases", pathParameter, typeParameter);
        }
    
        public virtual ObjectResult<AuthenticateUser_Result2> Usp_Ezy_AuthenticateUser(string pvc_ClientId, string pvc_UserId, string pvc_Password, string pvc_Database)
        {
            var pvc_ClientIdParameter = pvc_ClientId != null ?
                new ObjectParameter("Pvc_ClientId", pvc_ClientId) :
                new ObjectParameter("Pvc_ClientId", typeof(string));
    
            var pvc_UserIdParameter = pvc_UserId != null ?
                new ObjectParameter("Pvc_UserId", pvc_UserId) :
                new ObjectParameter("Pvc_UserId", typeof(string));
    
            var pvc_PasswordParameter = pvc_Password != null ?
                new ObjectParameter("Pvc_Password", pvc_Password) :
                new ObjectParameter("Pvc_Password", typeof(string));
    
            var pvc_DatabaseParameter = pvc_Database != null ?
                new ObjectParameter("Pvc_Database", pvc_Database) :
                new ObjectParameter("Pvc_Database", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AuthenticateUser_Result2>("Usp_Ezy_AuthenticateUser", pvc_ClientIdParameter, pvc_UserIdParameter, pvc_PasswordParameter, pvc_DatabaseParameter);
        }
    
        public virtual ObjectResult<AuthenticateUser_Result1> ValidateUserId(string pvc_ClientId, string pvc_UserId, string pvc_Password, string pvc_Database)
        {
            var pvc_ClientIdParameter = pvc_ClientId != null ?
                new ObjectParameter("Pvc_ClientId", pvc_ClientId) :
                new ObjectParameter("Pvc_ClientId", typeof(string));
    
            var pvc_UserIdParameter = pvc_UserId != null ?
                new ObjectParameter("Pvc_UserId", pvc_UserId) :
                new ObjectParameter("Pvc_UserId", typeof(string));
    
            var pvc_PasswordParameter = pvc_Password != null ?
                new ObjectParameter("Pvc_Password", pvc_Password) :
                new ObjectParameter("Pvc_Password", typeof(string));
    
            var pvc_DatabaseParameter = pvc_Database != null ?
                new ObjectParameter("Pvc_Database", pvc_Database) :
                new ObjectParameter("Pvc_Database", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AuthenticateUser_Result1>("ValidateUserId", pvc_ClientIdParameter, pvc_UserIdParameter, pvc_PasswordParameter, pvc_DatabaseParameter);
        }
    }
}
