//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBTS.View.Resources.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalCustomResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalCustomResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FBTS.View.Resources.ResourceFiles.GlobalCustomResource", typeof(GlobalCustomResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while trying to Set Access Rights!!.
        /// </summary>
        internal static string AccessRightFailed {
            get {
                return ResourceManager.GetString("AccessRightFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Rights Saved Successfully!!.
        /// </summary>
        internal static string AccessRightSaved {
            get {
                return ResourceManager.GetString("AccessRightSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while trying to save Accounts!.
        /// </summary>
        internal static string AccountFailed {
            get {
                return ResourceManager.GetString("AccountFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account has been Saved Successfully!!.
        /// </summary>
        internal static string AccountSaved {
            get {
                return ResourceManager.GetString("AccountSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative Part# cannot be same as actual part.
        /// </summary>
        internal static string AlternativePartValidation {
            get {
                return ResourceManager.GetString("AlternativePartValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while trying to save Attribute!.
        /// </summary>
        internal static string AnalysisFailed {
            get {
                return ResourceManager.GetString("AnalysisFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute has been Saved Successfully!.
        /// </summary>
        internal static string AnalysisSaved {
            get {
                return ResourceManager.GetString("AnalysisSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while trying to save Approved!.
        /// </summary>
        internal static string ApprovedFailed {
            get {
                return ResourceManager.GetString("ApprovedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved has been Saved Successfully!!.
        /// </summary>
        internal static string ApprovedSaved {
            get {
                return ResourceManager.GetString("ApprovedSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///   &lt;i class=&quot;toggle-accordion&quot;&gt;&lt;/i&gt;
        ///  .
        /// </summary>
        internal static string ArrowNode {
            get {
                return ResourceManager.GetString("ArrowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Update Failed.
        /// </summary>
        internal static string AttributeFailed {
            get {
                return ResourceManager.GetString("AttributeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes has been Saved Successfully!!.
        /// </summary>
        internal static string AttributeSaved {
            get {
                return ResourceManager.GetString("AttributeSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Update Failed!!.
        /// </summary>
        internal static string CategoryFailed {
            get {
                return ResourceManager.GetString("CategoryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category has been Saved Successfully.
        /// </summary>
        internal static string CategorySaved {
            get {
                return ResourceManager.GetString("CategorySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while trying to save Class!.
        /// </summary>
        internal static string ClassFailed {
            get {
                return ResourceManager.GetString("ClassFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class has been Saved Successfully!!.
        /// </summary>
        internal static string ClassSaved {
            get {
                return ResourceManager.GetString("ClassSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component Update Failed!!.
        /// </summary>
        internal static string ComponentFailed {
            get {
                return ResourceManager.GetString("ComponentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component has been Saved Successfully.
        /// </summary>
        internal static string ComponentSaved {
            get {
                return ResourceManager.GetString("ComponentSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while trying to Update Country!!.
        /// </summary>
        internal static string CountryFailed {
            get {
                return ResourceManager.GetString("CountryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country has been Saved Successfully!!.
        /// </summary>
        internal static string CountrySaved {
            get {
                return ResourceManager.GetString("CountrySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///         &lt;div class=&quot;form-group&quot;&gt;
        ///        &lt;div class=&quot;col-sm-5&quot;&gt;
        ///                                                 &lt;div class=&quot;pull-right&quot;&gt; {0}&lt;/div&gt;
        ///                                                &lt;/div&gt;
        ///                                               
        ///                                                &lt;div class=&quot;col-sm-7&quot;&gt;
        ///                                                    {1}
        ///                                                &lt;/div&gt;
        ///                                            &lt;/div&gt;                   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataRow {
            get {
                return ResourceManager.GetString("DataRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occured while trying to save Debriefing!.
        /// </summary>
        internal static string DebriefingFailed {
            get {
                return ResourceManager.GetString("DebriefingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debriefing has been Saved Successfully!!.
        /// </summary>
        internal static string DebriefingSaved {
            get {
                return ResourceManager.GetString("DebriefingSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed. Could not get SSOID..
        /// </summary>
        internal static string Default_lnkLogin_Click_Invalid_Userid_or_Password__ {
            get {
                return ResourceManager.GetString("Default_lnkLogin_Click_Invalid_Userid_or_Password__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed. Please contact your administrator to get more details about the failure.
        /// </summary>
        internal static string Default_lnkLogin_Click_Login_Failed_Error {
            get {
                return ResourceManager.GetString("Default_lnkLogin_Click_Login_Failed_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed. Could not get SSOID..
        /// </summary>
        internal static string Default_lnkLogin_Click_Please_Enter_Valid_userid_and_password__ {
            get {
                return ResourceManager.GetString("Default_lnkLogin_Click_Please_Enter_Valid_userid_and_password__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Userid!!.
        /// </summary>
        internal static string Default_txtUserId_TextChanged_Invalid_Userid__ {
            get {
                return ResourceManager.GetString("Default_txtUserId_TextChanged_Invalid_Userid__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while saving Designation!!.
        /// </summary>
        internal static string DesignationFailed {
            get {
                return ResourceManager.GetString("DesignationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation has been Saved Successfully.
        /// </summary>
        internal static string DesignationSaved {
            get {
                return ResourceManager.GetString("DesignationSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while trying to save Earning!.
        /// </summary>
        internal static string EarningFailed {
            get {
                return ResourceManager.GetString("EarningFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earning has been Saved Successfully!!.
        /// </summary>
        internal static string EarningSaved {
            get {
                return ResourceManager.GetString("EarningSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while trying to save Equipment!.
        /// </summary>
        internal static string EquipmentFailed {
            get {
                return ResourceManager.GetString("EquipmentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment saved successfully!.
        /// </summary>
        internal static string EquipmentSaved {
            get {
                return ResourceManager.GetString("EquipmentSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while trying to save Field Request!.
        /// </summary>
        internal static string FieldRequestFailed {
            get {
                return ResourceManager.GetString("FieldRequestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Request has been Saved Successfully!!.
        /// </summary>
        internal static string FieldRequestSaved {
            get {
                return ResourceManager.GetString("FieldRequestSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while trying to save Forecasting!.
        /// </summary>
        internal static string ForecastingFailed {
            get {
                return ResourceManager.GetString("ForecastingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forecasting has been Saved Successfully!!.
        /// </summary>
        internal static string ForecastingSave {
            get {
                return ResourceManager.GetString("ForecastingSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while trying to save Grade!.
        /// </summary>
        internal static string GradeFailed {
            get {
                return ResourceManager.GetString("GradeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade has been Saved Successfully!!.
        /// </summary>
        internal static string GradeSaved {
            get {
                return ResourceManager.GetString("GradeSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while trying to save Group!!.
        /// </summary>
        internal static string GroupFailed {
            get {
                return ResourceManager.GetString("GroupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group has been Saved Successfully!!.
        /// </summary>
        internal static string GroupSaved {
            get {
                return ResourceManager.GetString("GroupSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  
        ///      &lt;p class=&quot;nav-title&quot;&gt;{0}&lt;/p&gt;
        ///  .
        /// </summary>
        internal static string InfoMenu {
            get {
                return ResourceManager.GetString("InfoMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while trying to save Location!.
        /// </summary>
        internal static string LocationFailed {
            get {
                return ResourceManager.GetString("LocationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location has been Included Successfully!!.
        /// </summary>
        internal static string LocationIncluded {
            get {
                return ResourceManager.GetString("LocationIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while trying to Included Location!.
        /// </summary>
        internal static string LocationIncludedFailed {
            get {
                return ResourceManager.GetString("LocationIncludedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location has been Saved Successfully!!.
        /// </summary>
        internal static string LocationSaved {
            get {
                return ResourceManager.GetString("LocationSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location has been Suspended Successfully!!.
        /// </summary>
        internal static string LocationSuspended {
            get {
                return ResourceManager.GetString("LocationSuspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while trying to Suspend Location!.
        /// </summary>
        internal static string LocationSuspendedFailed {
            get {
                return ResourceManager.GetString("LocationSuspendedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///   &lt;li class=&quot;{0}&quot;&gt;
        ///        &lt;a class=&quot;{1}&quot; href=&quot;{2}&quot;&gt;
        ///            {3}
        ///            &lt;i class=&quot;{6}&quot;&gt;&lt;/i&gt;
        ///            &lt;span&gt;{4}&lt;/span&gt;
        ///        &lt;/a&gt;
        ///      {5}
        ///   &lt;/li&gt;
        ///  .
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while trying to save Maintenance!.
        /// </summary>
        internal static string MaintenanceFailed {
            get {
                return ResourceManager.GetString("MaintenanceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance has been Saved Successfully!!.
        /// </summary>
        internal static string MaintenanceSaved {
            get {
                return ResourceManager.GetString("MaintenanceSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Error occurred while trying to save Materials, Entered Part may exist!!.
        /// </summary>
        internal static string MaterialFailed {
            get {
                return ResourceManager.GetString("MaterialFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material has been Saved Successfully!!.
        /// </summary>
        internal static string MaterialSaved {
            get {
                return ResourceManager.GetString("MaterialSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while trying to save Menu!.
        /// </summary>
        internal static string MenuFailed {
            get {
                return ResourceManager.GetString("MenuFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu has been Saved Successfully!!.
        /// </summary>
        internal static string MenuSaved {
            get {
                return ResourceManager.GetString("MenuSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while trying to save Modality !.
        /// </summary>
        internal static string ModalityFailed {
            get {
                return ResourceManager.GetString("ModalityFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modality has been Included !!.
        /// </summary>
        internal static string ModalityIncluded {
            get {
                return ResourceManager.GetString("ModalityIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while trying to Include Modality!.
        /// </summary>
        internal static string ModalityIncludedFailed {
            get {
                return ResourceManager.GetString("ModalityIncludedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modality has been Saved Successfully!!.
        /// </summary>
        internal static string ModalitySaved {
            get {
                return ResourceManager.GetString("ModalitySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modality has been Suspended !!.
        /// </summary>
        internal static string ModalitySuspended {
            get {
                return ResourceManager.GetString("ModalitySuspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while trying to Suspend Modality!.
        /// </summary>
        internal static string ModalitySuspendedFailed {
            get {
                return ResourceManager.GetString("ModalitySuspendedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules Update Failed.
        /// </summary>
        internal static string ModuleFailed {
            get {
                return ResourceManager.GetString("ModuleFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules has been Saved Successfully!.
        /// </summary>
        internal static string ModuleSaved {
            get {
                return ResourceManager.GetString("ModuleSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while trying to save Next Stage!.
        /// </summary>
        internal static string NextStageFailed {
            get {
                return ResourceManager.GetString("NextStageFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Stage has been Saved Successfully!!.
        /// </summary>
        internal static string NextStageSaved {
            get {
                return ResourceManager.GetString("NextStageSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while trying to save Ordering Data !.
        /// </summary>
        internal static string OrderingFailed {
            get {
                return ResourceManager.GetString("OrderingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderingData has been Saved Successfully!!.
        /// </summary>
        internal static string OrderingSave {
            get {
                return ResourceManager.GetString("OrderingSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered help part no. Find more parts,Write some more help to find less parts.
        /// </summary>
        internal static string PartDdlFillValFaildMoreNoofRow {
            get {
                return ResourceManager.GetString("PartDdlFillValFaildMoreNoofRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part has been Included Successfully!!.
        /// </summary>
        internal static string PartIncluded {
            get {
                return ResourceManager.GetString("PartIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while trying to Included Part !.
        /// </summary>
        internal static string PartIncludedFailed {
            get {
                return ResourceManager.GetString("PartIncludedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered help part no. not matching part ,Write correct Part no. help.
        /// </summary>
        internal static string PartNotFoundFaild {
            get {
                return ResourceManager.GetString("PartNotFoundFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part has been Suspended Successfully!!.
        /// </summary>
        internal static string PartSuspended {
            get {
                return ResourceManager.GetString("PartSuspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while trying to Suspend Part !.
        /// </summary>
        internal static string PartSuspendedFalied {
            get {
                return ResourceManager.GetString("PartSuspendedFalied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while trying to save Party Master!.
        /// </summary>
        internal static string PartyMasterFailed {
            get {
                return ResourceManager.GetString("PartyMasterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Master has been Saved Successfully!.
        /// </summary>
        internal static string PartyMasterSaved {
            get {
                return ResourceManager.GetString("PartyMasterSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while trying to save Process Stage!.
        /// </summary>
        internal static string ProcessStageFailed {
            get {
                return ResourceManager.GetString("ProcessStageFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Stage has been Saved Successfully!!.
        /// </summary>
        internal static string ProcessStageSaved {
            get {
                return ResourceManager.GetString("ProcessStageSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while trying to save Profile!.
        /// </summary>
        internal static string ProfileFailed {
            get {
                return ResourceManager.GetString("ProfileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile has been Saved Successfully!!.
        /// </summary>
        internal static string ProfileSaved {
            get {
                return ResourceManager.GetString("ProfileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while trying to save Resource!.
        /// </summary>
        internal static string ResourceFailed {
            get {
                return ResourceManager.GetString("ResourceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource has been Saved Successfully!!.
        /// </summary>
        internal static string ResourceSaved {
            get {
                return ResourceManager.GetString("ResourceSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Update Failed.
        /// </summary>
        internal static string StageFailed {
            get {
                return ResourceManager.GetString("StageFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while trying to save Stages Master Data!.
        /// </summary>
        internal static string StageMasterFailed {
            get {
                return ResourceManager.GetString("StageMasterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage has been Saved Successfully!!.
        /// </summary>
        internal static string StageMasterSaved {
            get {
                return ResourceManager.GetString("StageMasterSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage has been Saved Successfully!!.
        /// </summary>
        internal static string StageSaved {
            get {
                return ResourceManager.GetString("StageSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while trying to Update State!!.
        /// </summary>
        internal static string StateFailed {
            get {
                return ResourceManager.GetString("StateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State has been Saved Successfully!!.
        /// </summary>
        internal static string StateSaved {
            get {
                return ResourceManager.GetString("StateSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///         &lt;li class=&quot;{0}&quot;&gt;&lt;a href=&quot;{1}&quot;&gt;&lt;span&gt;{2}&lt;/span&gt;&lt;/a&gt;&lt;/li&gt;                         
        ///  .
        /// </summary>
        internal static string SubMenu {
            get {
                return ResourceManager.GetString("SubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///   &lt;ul class=&quot;sub-menu&quot;&gt;
        ///        {0}
        ///    &lt;/ul&gt;
        ///  .
        /// </summary>
        internal static string SubMenuWrapper {
            get {
                return ResourceManager.GetString("SubMenuWrapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while trying to save SubModule.
        /// </summary>
        internal static string SubModuleFailed {
            get {
                return ResourceManager.GetString("SubModuleFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubModule has been Saved Successfully!!.
        /// </summary>
        internal static string SubModuleSaved {
            get {
                return ResourceManager.GetString("SubModuleSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while trying to save TeamData!.
        /// </summary>
        internal static string TeamDataFailed {
            get {
                return ResourceManager.GetString("TeamDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Data has been Saved Successfully!!.
        /// </summary>
        internal static string TeamDataSaved {
            get {
                return ResourceManager.GetString("TeamDataSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while trying to save Team Master Data!.
        /// </summary>
        internal static string TeamMasterFailed {
            get {
                return ResourceManager.GetString("TeamMasterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team has been Saved Successfully!!.
        /// </summary>
        internal static string TeamMasterSaved {
            get {
                return ResourceManager.GetString("TeamMasterSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while trying to save Tracking!.
        /// </summary>
        internal static string TrackingFailed {
            get {
                return ResourceManager.GetString("TrackingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking has been Saved Successfully!!.
        /// </summary>
        internal static string TrackingSaved {
            get {
                return ResourceManager.GetString("TrackingSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tv Template Update Failed.
        /// </summary>
        internal static string TVTemplateFailed {
            get {
                return ResourceManager.GetString("TVTemplateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV Template Saved Successfully!!.
        /// </summary>
        internal static string TVTemplateSaved {
            get {
                return ResourceManager.GetString("TVTemplateSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while trying to save Type!!.
        /// </summary>
        internal static string TypeFailed {
            get {
                return ResourceManager.GetString("TypeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type has been Saved Successfully!!.
        /// </summary>
        internal static string TypeSaved {
            get {
                return ResourceManager.GetString("TypeSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOM Update Failed.
        /// </summary>
        internal static string UOMFailed {
            get {
                return ResourceManager.GetString("UOMFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOM has been Included Successfully!!.
        /// </summary>
        internal static string UOMIncluded {
            get {
                return ResourceManager.GetString("UOMIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while trying to Include UOM!.
        /// </summary>
        internal static string UOMIncludedFailed {
            get {
                return ResourceManager.GetString("UOMIncludedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOM has been Saved Successfully!!.
        /// </summary>
        internal static string UOMSaved {
            get {
                return ResourceManager.GetString("UOMSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOM has been Suspended Successfully!!.
        /// </summary>
        internal static string UOMSuspended {
            get {
                return ResourceManager.GetString("UOMSuspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while trying to Suspend UOM!.
        /// </summary>
        internal static string UOMSuspendedFailed {
            get {
                return ResourceManager.GetString("UOMSuspendedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while trying to save UserProfile!.
        /// </summary>
        internal static string UserProfileFailed {
            get {
                return ResourceManager.GetString("UserProfileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserProfile has been Saved Successfully!!.
        /// </summary>
        internal static string UserProfileSaved {
            get {
                return ResourceManager.GetString("UserProfileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All Parts some parts are still in pandding check.
        /// </summary>
        internal static string ValidationAllSelect {
            get {
                return ResourceManager.GetString("ValidationAllSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification has been Saved Successfully!!.
        /// </summary>
        internal static string VerificationSaved {
            get {
                return ResourceManager.GetString("VerificationSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while trying to save Verification!.
        /// </summary>
        internal static string VerificayionFailed {
            get {
                return ResourceManager.GetString("VerificayionFailed", resourceCulture);
            }
        }
    }
}
