//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBTS.EntityFramework.Transactions
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TransactionEntities : DbContext
    {
        public TransactionEntities()
            : base("name=TransactionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int Usp_Ezy_Common_CheckRelations(string pvc_String, string pvc_Type)
        {
            var pvc_StringParameter = pvc_String != null ?
                new ObjectParameter("Pvc_String", pvc_String) :
                new ObjectParameter("Pvc_String", typeof(string));
    
            var pvc_TypeParameter = pvc_Type != null ?
                new ObjectParameter("Pvc_Type", pvc_Type) :
                new ObjectParameter("Pvc_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Usp_Ezy_Common_CheckRelations", pvc_StringParameter, pvc_TypeParameter);
        }
    
        public virtual int Usp_Ezy_Common_GenerateNewMasterId(string pvc_Code, string pvc_Type)
        {
            var pvc_CodeParameter = pvc_Code != null ?
                new ObjectParameter("Pvc_Code", pvc_Code) :
                new ObjectParameter("Pvc_Code", typeof(string));
    
            var pvc_TypeParameter = pvc_Type != null ?
                new ObjectParameter("Pvc_Type", pvc_Type) :
                new ObjectParameter("Pvc_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Usp_Ezy_Common_GenerateNewMasterId", pvc_CodeParameter, pvc_TypeParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_Common_RetriveMasterData_Result> Usp_Ezy_Common_RetriveMasterData(string pvc_Key, string pvc_Filter1, string pvc_Filter2, string pvc_Filter3, string pvc_Filter4, string pvc_MasterType)
        {
            var pvc_KeyParameter = pvc_Key != null ?
                new ObjectParameter("Pvc_Key", pvc_Key) :
                new ObjectParameter("Pvc_Key", typeof(string));
    
            var pvc_Filter1Parameter = pvc_Filter1 != null ?
                new ObjectParameter("Pvc_Filter1", pvc_Filter1) :
                new ObjectParameter("Pvc_Filter1", typeof(string));
    
            var pvc_Filter2Parameter = pvc_Filter2 != null ?
                new ObjectParameter("Pvc_Filter2", pvc_Filter2) :
                new ObjectParameter("Pvc_Filter2", typeof(string));
    
            var pvc_Filter3Parameter = pvc_Filter3 != null ?
                new ObjectParameter("Pvc_Filter3", pvc_Filter3) :
                new ObjectParameter("Pvc_Filter3", typeof(string));
    
            var pvc_Filter4Parameter = pvc_Filter4 != null ?
                new ObjectParameter("Pvc_Filter4", pvc_Filter4) :
                new ObjectParameter("Pvc_Filter4", typeof(string));
    
            var pvc_MasterTypeParameter = pvc_MasterType != null ?
                new ObjectParameter("Pvc_MasterType", pvc_MasterType) :
                new ObjectParameter("Pvc_MasterType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_Common_RetriveMasterData_Result>("Usp_Ezy_Common_RetriveMasterData", pvc_KeyParameter, pvc_Filter1Parameter, pvc_Filter2Parameter, pvc_Filter3Parameter, pvc_Filter4Parameter, pvc_MasterTypeParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_Common_RetriveOptions_Result> Usp_Ezy_Common_RetriveOptions(string pvc_Filter1, string pvc_Filter2, string pvc_Filter3, string pvc_MasterType)
        {
            var pvc_Filter1Parameter = pvc_Filter1 != null ?
                new ObjectParameter("Pvc_Filter1", pvc_Filter1) :
                new ObjectParameter("Pvc_Filter1", typeof(string));
    
            var pvc_Filter2Parameter = pvc_Filter2 != null ?
                new ObjectParameter("Pvc_Filter2", pvc_Filter2) :
                new ObjectParameter("Pvc_Filter2", typeof(string));
    
            var pvc_Filter3Parameter = pvc_Filter3 != null ?
                new ObjectParameter("Pvc_Filter3", pvc_Filter3) :
                new ObjectParameter("Pvc_Filter3", typeof(string));
    
            var pvc_MasterTypeParameter = pvc_MasterType != null ?
                new ObjectParameter("Pvc_MasterType", pvc_MasterType) :
                new ObjectParameter("Pvc_MasterType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_Common_RetriveOptions_Result>("Usp_Ezy_Common_RetriveOptions", pvc_Filter1Parameter, pvc_Filter2Parameter, pvc_Filter3Parameter, pvc_MasterTypeParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_CPanel_ManageUsers_Result> Usp_Ezy_CPanel_ManageUsers(Nullable<System.Guid> pvc_Key, string pvc_Keyword, string pvc_Type)
        {
            var pvc_KeyParameter = pvc_Key.HasValue ?
                new ObjectParameter("Pvc_Key", pvc_Key) :
                new ObjectParameter("Pvc_Key", typeof(System.Guid));
    
            var pvc_KeywordParameter = pvc_Keyword != null ?
                new ObjectParameter("Pvc_Keyword", pvc_Keyword) :
                new ObjectParameter("Pvc_Keyword", typeof(string));
    
            var pvc_TypeParameter = pvc_Type != null ?
                new ObjectParameter("Pvc_Type", pvc_Type) :
                new ObjectParameter("Pvc_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_CPanel_ManageUsers_Result>("Usp_Ezy_CPanel_ManageUsers", pvc_KeyParameter, pvc_KeywordParameter, pvc_TypeParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_CPanel_ManageUsersForm_Result> Usp_Ezy_CPanel_ManageUsersForm(Nullable<System.Guid> pvc_Key, string pvc_Keyword, string pvc_Type)
        {
            var pvc_KeyParameter = pvc_Key.HasValue ?
                new ObjectParameter("Pvc_Key", pvc_Key) :
                new ObjectParameter("Pvc_Key", typeof(System.Guid));
    
            var pvc_KeywordParameter = pvc_Keyword != null ?
                new ObjectParameter("Pvc_Keyword", pvc_Keyword) :
                new ObjectParameter("Pvc_Keyword", typeof(string));
    
            var pvc_TypeParameter = pvc_Type != null ?
                new ObjectParameter("Pvc_Type", pvc_Type) :
                new ObjectParameter("Pvc_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_CPanel_ManageUsersForm_Result>("Usp_Ezy_CPanel_ManageUsersForm", pvc_KeyParameter, pvc_KeywordParameter, pvc_TypeParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_Common_RetriveMasterCategoryList_Result> Usp_Ezy_Common_RetriveMasterCategoryList(string pvc_Key, string pvc_Filter1, string pvc_Filter2, string pvc_Filter3, string pvc_Filter4, string pvc_MasterType)
        {
            var pvc_KeyParameter = pvc_Key != null ?
                new ObjectParameter("Pvc_Key", pvc_Key) :
                new ObjectParameter("Pvc_Key", typeof(string));
    
            var pvc_Filter1Parameter = pvc_Filter1 != null ?
                new ObjectParameter("Pvc_Filter1", pvc_Filter1) :
                new ObjectParameter("Pvc_Filter1", typeof(string));
    
            var pvc_Filter2Parameter = pvc_Filter2 != null ?
                new ObjectParameter("Pvc_Filter2", pvc_Filter2) :
                new ObjectParameter("Pvc_Filter2", typeof(string));
    
            var pvc_Filter3Parameter = pvc_Filter3 != null ?
                new ObjectParameter("Pvc_Filter3", pvc_Filter3) :
                new ObjectParameter("Pvc_Filter3", typeof(string));
    
            var pvc_Filter4Parameter = pvc_Filter4 != null ?
                new ObjectParameter("Pvc_Filter4", pvc_Filter4) :
                new ObjectParameter("Pvc_Filter4", typeof(string));
    
            var pvc_MasterTypeParameter = pvc_MasterType != null ?
                new ObjectParameter("Pvc_MasterType", pvc_MasterType) :
                new ObjectParameter("Pvc_MasterType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_Common_RetriveMasterCategoryList_Result>("Usp_Ezy_Common_RetriveMasterCategoryList", pvc_KeyParameter, pvc_Filter1Parameter, pvc_Filter2Parameter, pvc_Filter3Parameter, pvc_Filter4Parameter, pvc_MasterTypeParameter);
        }
    
        public virtual ObjectResult<GetStagesByUser_Result> GetStagesByUser(string pvc_Key, string pvc_Filter1, string pvc_Filter2, string pvc_Filter3, string pvc_Filter4, string pvc_MasterType)
        {
            var pvc_KeyParameter = pvc_Key != null ?
                new ObjectParameter("Pvc_Key", pvc_Key) :
                new ObjectParameter("Pvc_Key", typeof(string));
    
            var pvc_Filter1Parameter = pvc_Filter1 != null ?
                new ObjectParameter("Pvc_Filter1", pvc_Filter1) :
                new ObjectParameter("Pvc_Filter1", typeof(string));
    
            var pvc_Filter2Parameter = pvc_Filter2 != null ?
                new ObjectParameter("Pvc_Filter2", pvc_Filter2) :
                new ObjectParameter("Pvc_Filter2", typeof(string));
    
            var pvc_Filter3Parameter = pvc_Filter3 != null ?
                new ObjectParameter("Pvc_Filter3", pvc_Filter3) :
                new ObjectParameter("Pvc_Filter3", typeof(string));
    
            var pvc_Filter4Parameter = pvc_Filter4 != null ?
                new ObjectParameter("Pvc_Filter4", pvc_Filter4) :
                new ObjectParameter("Pvc_Filter4", typeof(string));
    
            var pvc_MasterTypeParameter = pvc_MasterType != null ?
                new ObjectParameter("Pvc_MasterType", pvc_MasterType) :
                new ObjectParameter("Pvc_MasterType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStagesByUser_Result>("GetStagesByUser", pvc_KeyParameter, pvc_Filter1Parameter, pvc_Filter2Parameter, pvc_Filter3Parameter, pvc_Filter4Parameter, pvc_MasterTypeParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_Common_RetriveDdlData_Result> Usp_Ezy_Common_RetriveDdlData(string pvc_Key, string pvc_Filter1, string pvc_Filter2, string pvc_Filter3, string pvc_Filter4, string pvc_MasterType)
        {
            var pvc_KeyParameter = pvc_Key != null ?
                new ObjectParameter("Pvc_Key", pvc_Key) :
                new ObjectParameter("Pvc_Key", typeof(string));
    
            var pvc_Filter1Parameter = pvc_Filter1 != null ?
                new ObjectParameter("Pvc_Filter1", pvc_Filter1) :
                new ObjectParameter("Pvc_Filter1", typeof(string));
    
            var pvc_Filter2Parameter = pvc_Filter2 != null ?
                new ObjectParameter("Pvc_Filter2", pvc_Filter2) :
                new ObjectParameter("Pvc_Filter2", typeof(string));
    
            var pvc_Filter3Parameter = pvc_Filter3 != null ?
                new ObjectParameter("Pvc_Filter3", pvc_Filter3) :
                new ObjectParameter("Pvc_Filter3", typeof(string));
    
            var pvc_Filter4Parameter = pvc_Filter4 != null ?
                new ObjectParameter("Pvc_Filter4", pvc_Filter4) :
                new ObjectParameter("Pvc_Filter4", typeof(string));
    
            var pvc_MasterTypeParameter = pvc_MasterType != null ?
                new ObjectParameter("Pvc_MasterType", pvc_MasterType) :
                new ObjectParameter("Pvc_MasterType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_Common_RetriveDdlData_Result>("Usp_Ezy_Common_RetriveDdlData", pvc_KeyParameter, pvc_Filter1Parameter, pvc_Filter2Parameter, pvc_Filter3Parameter, pvc_Filter4Parameter, pvc_MasterTypeParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_Common_RetriveMasterTeamList_Result> Usp_Ezy_Common_RetriveMasterTeamList(string pvc_Key, string pvc_Filter1, string pvc_Filter2, string pvc_Filter3, string pvc_Filter4, string pvc_MasterType)
        {
            var pvc_KeyParameter = pvc_Key != null ?
                new ObjectParameter("Pvc_Key", pvc_Key) :
                new ObjectParameter("Pvc_Key", typeof(string));
    
            var pvc_Filter1Parameter = pvc_Filter1 != null ?
                new ObjectParameter("Pvc_Filter1", pvc_Filter1) :
                new ObjectParameter("Pvc_Filter1", typeof(string));
    
            var pvc_Filter2Parameter = pvc_Filter2 != null ?
                new ObjectParameter("Pvc_Filter2", pvc_Filter2) :
                new ObjectParameter("Pvc_Filter2", typeof(string));
    
            var pvc_Filter3Parameter = pvc_Filter3 != null ?
                new ObjectParameter("Pvc_Filter3", pvc_Filter3) :
                new ObjectParameter("Pvc_Filter3", typeof(string));
    
            var pvc_Filter4Parameter = pvc_Filter4 != null ?
                new ObjectParameter("Pvc_Filter4", pvc_Filter4) :
                new ObjectParameter("Pvc_Filter4", typeof(string));
    
            var pvc_MasterTypeParameter = pvc_MasterType != null ?
                new ObjectParameter("Pvc_MasterType", pvc_MasterType) :
                new ObjectParameter("Pvc_MasterType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_Common_RetriveMasterTeamList_Result>("Usp_Ezy_Common_RetriveMasterTeamList", pvc_KeyParameter, pvc_Filter1Parameter, pvc_Filter2Parameter, pvc_Filter3Parameter, pvc_Filter4Parameter, pvc_MasterTypeParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_Common_RetriveMasterTeamForm_Result> Usp_Ezy_Common_RetriveMasterTeamForm(string pvc_Key, string pvc_Filter1, string pvc_Filter2, string pvc_Filter3, string pvc_Filter4, string pvc_MasterType)
        {
            var pvc_KeyParameter = pvc_Key != null ?
                new ObjectParameter("Pvc_Key", pvc_Key) :
                new ObjectParameter("Pvc_Key", typeof(string));
    
            var pvc_Filter1Parameter = pvc_Filter1 != null ?
                new ObjectParameter("Pvc_Filter1", pvc_Filter1) :
                new ObjectParameter("Pvc_Filter1", typeof(string));
    
            var pvc_Filter2Parameter = pvc_Filter2 != null ?
                new ObjectParameter("Pvc_Filter2", pvc_Filter2) :
                new ObjectParameter("Pvc_Filter2", typeof(string));
    
            var pvc_Filter3Parameter = pvc_Filter3 != null ?
                new ObjectParameter("Pvc_Filter3", pvc_Filter3) :
                new ObjectParameter("Pvc_Filter3", typeof(string));
    
            var pvc_Filter4Parameter = pvc_Filter4 != null ?
                new ObjectParameter("Pvc_Filter4", pvc_Filter4) :
                new ObjectParameter("Pvc_Filter4", typeof(string));
    
            var pvc_MasterTypeParameter = pvc_MasterType != null ?
                new ObjectParameter("Pvc_MasterType", pvc_MasterType) :
                new ObjectParameter("Pvc_MasterType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_Common_RetriveMasterTeamForm_Result>("Usp_Ezy_Common_RetriveMasterTeamForm", pvc_KeyParameter, pvc_Filter1Parameter, pvc_Filter2Parameter, pvc_Filter3Parameter, pvc_Filter4Parameter, pvc_MasterTypeParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_Common_RetriveMasterMCatDetl_Result> Usp_Ezy_Common_RetriveMasterMCatDetl(string pvc_Key, string pvc_Filter1, string pvc_Filter2, string pvc_Filter3, string pvc_Filter4, string pvc_MasterType)
        {
            var pvc_KeyParameter = pvc_Key != null ?
                new ObjectParameter("Pvc_Key", pvc_Key) :
                new ObjectParameter("Pvc_Key", typeof(string));
    
            var pvc_Filter1Parameter = pvc_Filter1 != null ?
                new ObjectParameter("Pvc_Filter1", pvc_Filter1) :
                new ObjectParameter("Pvc_Filter1", typeof(string));
    
            var pvc_Filter2Parameter = pvc_Filter2 != null ?
                new ObjectParameter("Pvc_Filter2", pvc_Filter2) :
                new ObjectParameter("Pvc_Filter2", typeof(string));
    
            var pvc_Filter3Parameter = pvc_Filter3 != null ?
                new ObjectParameter("Pvc_Filter3", pvc_Filter3) :
                new ObjectParameter("Pvc_Filter3", typeof(string));
    
            var pvc_Filter4Parameter = pvc_Filter4 != null ?
                new ObjectParameter("Pvc_Filter4", pvc_Filter4) :
                new ObjectParameter("Pvc_Filter4", typeof(string));
    
            var pvc_MasterTypeParameter = pvc_MasterType != null ?
                new ObjectParameter("Pvc_MasterType", pvc_MasterType) :
                new ObjectParameter("Pvc_MasterType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_Common_RetriveMasterMCatDetl_Result>("Usp_Ezy_Common_RetriveMasterMCatDetl", pvc_KeyParameter, pvc_Filter1Parameter, pvc_Filter2Parameter, pvc_Filter3Parameter, pvc_Filter4Parameter, pvc_MasterTypeParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_CPanel_MenuAccessRights_Result> Usp_Ezy_CPanel_MenuAccessRights(Nullable<System.Guid> pvc_UserId, string pvc_DesignationId)
        {
            var pvc_UserIdParameter = pvc_UserId.HasValue ?
                new ObjectParameter("Pvc_UserId", pvc_UserId) :
                new ObjectParameter("Pvc_UserId", typeof(System.Guid));
    
            var pvc_DesignationIdParameter = pvc_DesignationId != null ?
                new ObjectParameter("Pvc_DesignationId", pvc_DesignationId) :
                new ObjectParameter("Pvc_DesignationId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_CPanel_MenuAccessRights_Result>("Usp_Ezy_CPanel_MenuAccessRights", pvc_UserIdParameter, pvc_DesignationIdParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_Common_RetriveMaterials_Result> Usp_Ezy_Common_RetriveMaterials(string pvc_Key, string pvc_Filter1, string pvc_Filter2, string pvc_Filter3, string pvc_Filter4, string pvc_MasterType)
        {
            var pvc_KeyParameter = pvc_Key != null ?
                new ObjectParameter("Pvc_Key", pvc_Key) :
                new ObjectParameter("Pvc_Key", typeof(string));
    
            var pvc_Filter1Parameter = pvc_Filter1 != null ?
                new ObjectParameter("Pvc_Filter1", pvc_Filter1) :
                new ObjectParameter("Pvc_Filter1", typeof(string));
    
            var pvc_Filter2Parameter = pvc_Filter2 != null ?
                new ObjectParameter("Pvc_Filter2", pvc_Filter2) :
                new ObjectParameter("Pvc_Filter2", typeof(string));
    
            var pvc_Filter3Parameter = pvc_Filter3 != null ?
                new ObjectParameter("Pvc_Filter3", pvc_Filter3) :
                new ObjectParameter("Pvc_Filter3", typeof(string));
    
            var pvc_Filter4Parameter = pvc_Filter4 != null ?
                new ObjectParameter("Pvc_Filter4", pvc_Filter4) :
                new ObjectParameter("Pvc_Filter4", typeof(string));
    
            var pvc_MasterTypeParameter = pvc_MasterType != null ?
                new ObjectParameter("Pvc_MasterType", pvc_MasterType) :
                new ObjectParameter("Pvc_MasterType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_Common_RetriveMaterials_Result>("Usp_Ezy_Common_RetriveMaterials", pvc_KeyParameter, pvc_Filter1Parameter, pvc_Filter2Parameter, pvc_Filter3Parameter, pvc_Filter4Parameter, pvc_MasterTypeParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_Operations_ManageAccounts_Result> Usp_Ezy_Operations_ManageAccounts(string pvc_Key, string pvc_Filter1, string pvc_Filter2, string pvc_Filter3, string pvc_Filter4, string pvc_Type)
        {
            var pvc_KeyParameter = pvc_Key != null ?
                new ObjectParameter("Pvc_Key", pvc_Key) :
                new ObjectParameter("Pvc_Key", typeof(string));
    
            var pvc_Filter1Parameter = pvc_Filter1 != null ?
                new ObjectParameter("Pvc_Filter1", pvc_Filter1) :
                new ObjectParameter("Pvc_Filter1", typeof(string));
    
            var pvc_Filter2Parameter = pvc_Filter2 != null ?
                new ObjectParameter("Pvc_Filter2", pvc_Filter2) :
                new ObjectParameter("Pvc_Filter2", typeof(string));
    
            var pvc_Filter3Parameter = pvc_Filter3 != null ?
                new ObjectParameter("Pvc_Filter3", pvc_Filter3) :
                new ObjectParameter("Pvc_Filter3", typeof(string));
    
            var pvc_Filter4Parameter = pvc_Filter4 != null ?
                new ObjectParameter("Pvc_Filter4", pvc_Filter4) :
                new ObjectParameter("Pvc_Filter4", typeof(string));
    
            var pvc_TypeParameter = pvc_Type != null ?
                new ObjectParameter("Pvc_Type", pvc_Type) :
                new ObjectParameter("Pvc_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_Operations_ManageAccounts_Result>("Usp_Ezy_Operations_ManageAccounts", pvc_KeyParameter, pvc_Filter1Parameter, pvc_Filter2Parameter, pvc_Filter3Parameter, pvc_Filter4Parameter, pvc_TypeParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_Operations_ManageAccountsForm_Result> Usp_Ezy_Operations_ManageAccountsForm(string pvc_Key, string pvc_Filter1, string pvc_Filter2, string pvc_Filter3, string pvc_Filter4, string pvc_Type)
        {
            var pvc_KeyParameter = pvc_Key != null ?
                new ObjectParameter("Pvc_Key", pvc_Key) :
                new ObjectParameter("Pvc_Key", typeof(string));
    
            var pvc_Filter1Parameter = pvc_Filter1 != null ?
                new ObjectParameter("Pvc_Filter1", pvc_Filter1) :
                new ObjectParameter("Pvc_Filter1", typeof(string));
    
            var pvc_Filter2Parameter = pvc_Filter2 != null ?
                new ObjectParameter("Pvc_Filter2", pvc_Filter2) :
                new ObjectParameter("Pvc_Filter2", typeof(string));
    
            var pvc_Filter3Parameter = pvc_Filter3 != null ?
                new ObjectParameter("Pvc_Filter3", pvc_Filter3) :
                new ObjectParameter("Pvc_Filter3", typeof(string));
    
            var pvc_Filter4Parameter = pvc_Filter4 != null ?
                new ObjectParameter("Pvc_Filter4", pvc_Filter4) :
                new ObjectParameter("Pvc_Filter4", typeof(string));
    
            var pvc_TypeParameter = pvc_Type != null ?
                new ObjectParameter("Pvc_Type", pvc_Type) :
                new ObjectParameter("Pvc_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_Operations_ManageAccountsForm_Result>("Usp_Ezy_Operations_ManageAccountsForm", pvc_KeyParameter, pvc_Filter1Parameter, pvc_Filter2Parameter, pvc_Filter3Parameter, pvc_Filter4Parameter, pvc_TypeParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_Common_RetriveMaterialsForm_Result> Usp_Ezy_Common_RetriveMaterialsForm(string pvc_Key, string pvc_Filter1, string pvc_Filter2, string pvc_Filter3, string pvc_Filter4, string pvc_MasterType)
        {
            var pvc_KeyParameter = pvc_Key != null ?
                new ObjectParameter("Pvc_Key", pvc_Key) :
                new ObjectParameter("Pvc_Key", typeof(string));
    
            var pvc_Filter1Parameter = pvc_Filter1 != null ?
                new ObjectParameter("Pvc_Filter1", pvc_Filter1) :
                new ObjectParameter("Pvc_Filter1", typeof(string));
    
            var pvc_Filter2Parameter = pvc_Filter2 != null ?
                new ObjectParameter("Pvc_Filter2", pvc_Filter2) :
                new ObjectParameter("Pvc_Filter2", typeof(string));
    
            var pvc_Filter3Parameter = pvc_Filter3 != null ?
                new ObjectParameter("Pvc_Filter3", pvc_Filter3) :
                new ObjectParameter("Pvc_Filter3", typeof(string));
    
            var pvc_Filter4Parameter = pvc_Filter4 != null ?
                new ObjectParameter("Pvc_Filter4", pvc_Filter4) :
                new ObjectParameter("Pvc_Filter4", typeof(string));
    
            var pvc_MasterTypeParameter = pvc_MasterType != null ?
                new ObjectParameter("Pvc_MasterType", pvc_MasterType) :
                new ObjectParameter("Pvc_MasterType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_Common_RetriveMaterialsForm_Result>("Usp_Ezy_Common_RetriveMaterialsForm", pvc_KeyParameter, pvc_Filter1Parameter, pvc_Filter2Parameter, pvc_Filter3Parameter, pvc_Filter4Parameter, pvc_MasterTypeParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_Common_RetriveMasterReferencesList_Result> Usp_Ezy_Common_RetriveMasterReferencesList(string pvc_Key, string pvc_Filter1, string pvc_Filter2, string pvc_Filter3, string pvc_Filter4, string pvc_MasterType)
        {
            var pvc_KeyParameter = pvc_Key != null ?
                new ObjectParameter("Pvc_Key", pvc_Key) :
                new ObjectParameter("Pvc_Key", typeof(string));
    
            var pvc_Filter1Parameter = pvc_Filter1 != null ?
                new ObjectParameter("Pvc_Filter1", pvc_Filter1) :
                new ObjectParameter("Pvc_Filter1", typeof(string));
    
            var pvc_Filter2Parameter = pvc_Filter2 != null ?
                new ObjectParameter("Pvc_Filter2", pvc_Filter2) :
                new ObjectParameter("Pvc_Filter2", typeof(string));
    
            var pvc_Filter3Parameter = pvc_Filter3 != null ?
                new ObjectParameter("Pvc_Filter3", pvc_Filter3) :
                new ObjectParameter("Pvc_Filter3", typeof(string));
    
            var pvc_Filter4Parameter = pvc_Filter4 != null ?
                new ObjectParameter("Pvc_Filter4", pvc_Filter4) :
                new ObjectParameter("Pvc_Filter4", typeof(string));
    
            var pvc_MasterTypeParameter = pvc_MasterType != null ?
                new ObjectParameter("Pvc_MasterType", pvc_MasterType) :
                new ObjectParameter("Pvc_MasterType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_Common_RetriveMasterReferencesList_Result>("Usp_Ezy_Common_RetriveMasterReferencesList", pvc_KeyParameter, pvc_Filter1Parameter, pvc_Filter2Parameter, pvc_Filter3Parameter, pvc_Filter4Parameter, pvc_MasterTypeParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_Common_GenNewMasterNumber_Result> Usp_Ezy_Common_GenNewMasterNumber(string pvc_Code, string pvc_Type)
        {
            var pvc_CodeParameter = pvc_Code != null ?
                new ObjectParameter("Pvc_Code", pvc_Code) :
                new ObjectParameter("Pvc_Code", typeof(string));
    
            var pvc_TypeParameter = pvc_Type != null ?
                new ObjectParameter("Pvc_Type", pvc_Type) :
                new ObjectParameter("Pvc_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_Common_GenNewMasterNumber_Result>("Usp_Ezy_Common_GenNewMasterNumber", pvc_CodeParameter, pvc_TypeParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_Txn_RetriveTxnData_Result> Usp_Ezy_Txn_RetriveTxnData(string pvc_TxnNumber, string pvc_Filter1, string pvc_Filter2, string pvc_Filter3, string pvc_Filter4, string pvc_Filter5, string pvc_Filter6, string pvc_Type)
        {
            var pvc_TxnNumberParameter = pvc_TxnNumber != null ?
                new ObjectParameter("Pvc_TxnNumber", pvc_TxnNumber) :
                new ObjectParameter("Pvc_TxnNumber", typeof(string));
    
            var pvc_Filter1Parameter = pvc_Filter1 != null ?
                new ObjectParameter("Pvc_Filter1", pvc_Filter1) :
                new ObjectParameter("Pvc_Filter1", typeof(string));
    
            var pvc_Filter2Parameter = pvc_Filter2 != null ?
                new ObjectParameter("Pvc_Filter2", pvc_Filter2) :
                new ObjectParameter("Pvc_Filter2", typeof(string));
    
            var pvc_Filter3Parameter = pvc_Filter3 != null ?
                new ObjectParameter("Pvc_Filter3", pvc_Filter3) :
                new ObjectParameter("Pvc_Filter3", typeof(string));
    
            var pvc_Filter4Parameter = pvc_Filter4 != null ?
                new ObjectParameter("Pvc_Filter4", pvc_Filter4) :
                new ObjectParameter("Pvc_Filter4", typeof(string));
    
            var pvc_Filter5Parameter = pvc_Filter5 != null ?
                new ObjectParameter("Pvc_Filter5", pvc_Filter5) :
                new ObjectParameter("Pvc_Filter5", typeof(string));
    
            var pvc_Filter6Parameter = pvc_Filter6 != null ?
                new ObjectParameter("Pvc_Filter6", pvc_Filter6) :
                new ObjectParameter("Pvc_Filter6", typeof(string));
    
            var pvc_TypeParameter = pvc_Type != null ?
                new ObjectParameter("Pvc_Type", pvc_Type) :
                new ObjectParameter("Pvc_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_Txn_RetriveTxnData_Result>("Usp_Ezy_Txn_RetriveTxnData", pvc_TxnNumberParameter, pvc_Filter1Parameter, pvc_Filter2Parameter, pvc_Filter3Parameter, pvc_Filter4Parameter, pvc_Filter5Parameter, pvc_Filter6Parameter, pvc_TypeParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_Txn_RetriveTxnDataOrderForm_Result> Usp_Ezy_Txn_RetriveTxnDataOrderForm(string pvc_TxnNumber, string pvc_Filter1, string pvc_Filter2, string pvc_Filter3, string pvc_Filter4, string pvc_Filter5, string pvc_Filter6, string pvc_Type)
        {
            var pvc_TxnNumberParameter = pvc_TxnNumber != null ?
                new ObjectParameter("Pvc_TxnNumber", pvc_TxnNumber) :
                new ObjectParameter("Pvc_TxnNumber", typeof(string));
    
            var pvc_Filter1Parameter = pvc_Filter1 != null ?
                new ObjectParameter("Pvc_Filter1", pvc_Filter1) :
                new ObjectParameter("Pvc_Filter1", typeof(string));
    
            var pvc_Filter2Parameter = pvc_Filter2 != null ?
                new ObjectParameter("Pvc_Filter2", pvc_Filter2) :
                new ObjectParameter("Pvc_Filter2", typeof(string));
    
            var pvc_Filter3Parameter = pvc_Filter3 != null ?
                new ObjectParameter("Pvc_Filter3", pvc_Filter3) :
                new ObjectParameter("Pvc_Filter3", typeof(string));
    
            var pvc_Filter4Parameter = pvc_Filter4 != null ?
                new ObjectParameter("Pvc_Filter4", pvc_Filter4) :
                new ObjectParameter("Pvc_Filter4", typeof(string));
    
            var pvc_Filter5Parameter = pvc_Filter5 != null ?
                new ObjectParameter("Pvc_Filter5", pvc_Filter5) :
                new ObjectParameter("Pvc_Filter5", typeof(string));
    
            var pvc_Filter6Parameter = pvc_Filter6 != null ?
                new ObjectParameter("Pvc_Filter6", pvc_Filter6) :
                new ObjectParameter("Pvc_Filter6", typeof(string));
    
            var pvc_TypeParameter = pvc_Type != null ?
                new ObjectParameter("Pvc_Type", pvc_Type) :
                new ObjectParameter("Pvc_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_Txn_RetriveTxnDataOrderForm_Result>("Usp_Ezy_Txn_RetriveTxnDataOrderForm", pvc_TxnNumberParameter, pvc_Filter1Parameter, pvc_Filter2Parameter, pvc_Filter3Parameter, pvc_Filter4Parameter, pvc_Filter5Parameter, pvc_Filter6Parameter, pvc_TypeParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_Inventory_ManageMaterials_Result> Usp_Ezy_Inventory_ManageMaterials(string pvc_Key, string pvc_Filter1, string pvc_Filter2, string pvc_Filter3, string pvc_Filter4, string pvc_Type)
        {
            var pvc_KeyParameter = pvc_Key != null ?
                new ObjectParameter("Pvc_Key", pvc_Key) :
                new ObjectParameter("Pvc_Key", typeof(string));
    
            var pvc_Filter1Parameter = pvc_Filter1 != null ?
                new ObjectParameter("Pvc_Filter1", pvc_Filter1) :
                new ObjectParameter("Pvc_Filter1", typeof(string));
    
            var pvc_Filter2Parameter = pvc_Filter2 != null ?
                new ObjectParameter("Pvc_Filter2", pvc_Filter2) :
                new ObjectParameter("Pvc_Filter2", typeof(string));
    
            var pvc_Filter3Parameter = pvc_Filter3 != null ?
                new ObjectParameter("Pvc_Filter3", pvc_Filter3) :
                new ObjectParameter("Pvc_Filter3", typeof(string));
    
            var pvc_Filter4Parameter = pvc_Filter4 != null ?
                new ObjectParameter("Pvc_Filter4", pvc_Filter4) :
                new ObjectParameter("Pvc_Filter4", typeof(string));
    
            var pvc_TypeParameter = pvc_Type != null ?
                new ObjectParameter("Pvc_Type", pvc_Type) :
                new ObjectParameter("Pvc_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_Inventory_ManageMaterials_Result>("Usp_Ezy_Inventory_ManageMaterials", pvc_KeyParameter, pvc_Filter1Parameter, pvc_Filter2Parameter, pvc_Filter3Parameter, pvc_Filter4Parameter, pvc_TypeParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_Txn_RetriveFolloupList_Result> Usp_Ezy_Txn_RetriveFolloupList(string pvc_TxnNumber, string pvc_Filter1, string pvc_Filter2, string pvc_Filter3, string pvc_Filter4, string pvc_Filter5, string pvc_Filter6, string pvc_Type)
        {
            var pvc_TxnNumberParameter = pvc_TxnNumber != null ?
                new ObjectParameter("Pvc_TxnNumber", pvc_TxnNumber) :
                new ObjectParameter("Pvc_TxnNumber", typeof(string));
    
            var pvc_Filter1Parameter = pvc_Filter1 != null ?
                new ObjectParameter("Pvc_Filter1", pvc_Filter1) :
                new ObjectParameter("Pvc_Filter1", typeof(string));
    
            var pvc_Filter2Parameter = pvc_Filter2 != null ?
                new ObjectParameter("Pvc_Filter2", pvc_Filter2) :
                new ObjectParameter("Pvc_Filter2", typeof(string));
    
            var pvc_Filter3Parameter = pvc_Filter3 != null ?
                new ObjectParameter("Pvc_Filter3", pvc_Filter3) :
                new ObjectParameter("Pvc_Filter3", typeof(string));
    
            var pvc_Filter4Parameter = pvc_Filter4 != null ?
                new ObjectParameter("Pvc_Filter4", pvc_Filter4) :
                new ObjectParameter("Pvc_Filter4", typeof(string));
    
            var pvc_Filter5Parameter = pvc_Filter5 != null ?
                new ObjectParameter("Pvc_Filter5", pvc_Filter5) :
                new ObjectParameter("Pvc_Filter5", typeof(string));
    
            var pvc_Filter6Parameter = pvc_Filter6 != null ?
                new ObjectParameter("Pvc_Filter6", pvc_Filter6) :
                new ObjectParameter("Pvc_Filter6", typeof(string));
    
            var pvc_TypeParameter = pvc_Type != null ?
                new ObjectParameter("Pvc_Type", pvc_Type) :
                new ObjectParameter("Pvc_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_Txn_RetriveFolloupList_Result>("Usp_Ezy_Txn_RetriveFolloupList", pvc_TxnNumberParameter, pvc_Filter1Parameter, pvc_Filter2Parameter, pvc_Filter3Parameter, pvc_Filter4Parameter, pvc_Filter5Parameter, pvc_Filter6Parameter, pvc_TypeParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_Txn_RetriveFolloupFormData_Result> Usp_Ezy_Txn_RetriveFolloupFormData(string pvc_TxnNumber, string pvc_Filter1, string pvc_Filter2, string pvc_Filter3, string pvc_Filter4, string pvc_Filter5, string pvc_Filter6, string pvc_Type)
        {
            var pvc_TxnNumberParameter = pvc_TxnNumber != null ?
                new ObjectParameter("Pvc_TxnNumber", pvc_TxnNumber) :
                new ObjectParameter("Pvc_TxnNumber", typeof(string));
    
            var pvc_Filter1Parameter = pvc_Filter1 != null ?
                new ObjectParameter("Pvc_Filter1", pvc_Filter1) :
                new ObjectParameter("Pvc_Filter1", typeof(string));
    
            var pvc_Filter2Parameter = pvc_Filter2 != null ?
                new ObjectParameter("Pvc_Filter2", pvc_Filter2) :
                new ObjectParameter("Pvc_Filter2", typeof(string));
    
            var pvc_Filter3Parameter = pvc_Filter3 != null ?
                new ObjectParameter("Pvc_Filter3", pvc_Filter3) :
                new ObjectParameter("Pvc_Filter3", typeof(string));
    
            var pvc_Filter4Parameter = pvc_Filter4 != null ?
                new ObjectParameter("Pvc_Filter4", pvc_Filter4) :
                new ObjectParameter("Pvc_Filter4", typeof(string));
    
            var pvc_Filter5Parameter = pvc_Filter5 != null ?
                new ObjectParameter("Pvc_Filter5", pvc_Filter5) :
                new ObjectParameter("Pvc_Filter5", typeof(string));
    
            var pvc_Filter6Parameter = pvc_Filter6 != null ?
                new ObjectParameter("Pvc_Filter6", pvc_Filter6) :
                new ObjectParameter("Pvc_Filter6", typeof(string));
    
            var pvc_TypeParameter = pvc_Type != null ?
                new ObjectParameter("Pvc_Type", pvc_Type) :
                new ObjectParameter("Pvc_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_Txn_RetriveFolloupFormData_Result>("Usp_Ezy_Txn_RetriveFolloupFormData", pvc_TxnNumberParameter, pvc_Filter1Parameter, pvc_Filter2Parameter, pvc_Filter3Parameter, pvc_Filter4Parameter, pvc_Filter5Parameter, pvc_Filter6Parameter, pvc_TypeParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_Txn_RetriveReference_Result1> Usp_Ezy_Txn_RetriveReference(string pvc_TxnNumber, string pvc_Filter1, string pvc_Filter2, string pvc_Filter3, string pvc_Filter4, string pvc_Filter5, string pvc_Filter6, string pvc_Type)
        {
            var pvc_TxnNumberParameter = pvc_TxnNumber != null ?
                new ObjectParameter("Pvc_TxnNumber", pvc_TxnNumber) :
                new ObjectParameter("Pvc_TxnNumber", typeof(string));
    
            var pvc_Filter1Parameter = pvc_Filter1 != null ?
                new ObjectParameter("Pvc_Filter1", pvc_Filter1) :
                new ObjectParameter("Pvc_Filter1", typeof(string));
    
            var pvc_Filter2Parameter = pvc_Filter2 != null ?
                new ObjectParameter("Pvc_Filter2", pvc_Filter2) :
                new ObjectParameter("Pvc_Filter2", typeof(string));
    
            var pvc_Filter3Parameter = pvc_Filter3 != null ?
                new ObjectParameter("Pvc_Filter3", pvc_Filter3) :
                new ObjectParameter("Pvc_Filter3", typeof(string));
    
            var pvc_Filter4Parameter = pvc_Filter4 != null ?
                new ObjectParameter("Pvc_Filter4", pvc_Filter4) :
                new ObjectParameter("Pvc_Filter4", typeof(string));
    
            var pvc_Filter5Parameter = pvc_Filter5 != null ?
                new ObjectParameter("Pvc_Filter5", pvc_Filter5) :
                new ObjectParameter("Pvc_Filter5", typeof(string));
    
            var pvc_Filter6Parameter = pvc_Filter6 != null ?
                new ObjectParameter("Pvc_Filter6", pvc_Filter6) :
                new ObjectParameter("Pvc_Filter6", typeof(string));
    
            var pvc_TypeParameter = pvc_Type != null ?
                new ObjectParameter("Pvc_Type", pvc_Type) :
                new ObjectParameter("Pvc_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_Txn_RetriveReference_Result1>("Usp_Ezy_Txn_RetriveReference", pvc_TxnNumberParameter, pvc_Filter1Parameter, pvc_Filter2Parameter, pvc_Filter3Parameter, pvc_Filter4Parameter, pvc_Filter5Parameter, pvc_Filter6Parameter, pvc_TypeParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_CPanel_ManageCompanyProfile_Result> Usp_Ezy_CPanel_ManageCompanyProfile(string pvc_Key, string pvc_CType, string pvc_Keyword, string pvc_Type)
        {
            var pvc_KeyParameter = pvc_Key != null ?
                new ObjectParameter("Pvc_Key", pvc_Key) :
                new ObjectParameter("Pvc_Key", typeof(string));
    
            var pvc_CTypeParameter = pvc_CType != null ?
                new ObjectParameter("Pvc_CType", pvc_CType) :
                new ObjectParameter("Pvc_CType", typeof(string));
    
            var pvc_KeywordParameter = pvc_Keyword != null ?
                new ObjectParameter("Pvc_Keyword", pvc_Keyword) :
                new ObjectParameter("Pvc_Keyword", typeof(string));
    
            var pvc_TypeParameter = pvc_Type != null ?
                new ObjectParameter("Pvc_Type", pvc_Type) :
                new ObjectParameter("Pvc_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_CPanel_ManageCompanyProfile_Result>("Usp_Ezy_CPanel_ManageCompanyProfile", pvc_KeyParameter, pvc_CTypeParameter, pvc_KeywordParameter, pvc_TypeParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_CPanel_ManageCompanyProfile_Form_Result> Usp_Ezy_CPanel_ManageCompanyProfile_Form(string pvc_Key, string pvc_CType, string pvc_Keyword, string pvc_Type)
        {
            var pvc_KeyParameter = pvc_Key != null ?
                new ObjectParameter("Pvc_Key", pvc_Key) :
                new ObjectParameter("Pvc_Key", typeof(string));
    
            var pvc_CTypeParameter = pvc_CType != null ?
                new ObjectParameter("Pvc_CType", pvc_CType) :
                new ObjectParameter("Pvc_CType", typeof(string));
    
            var pvc_KeywordParameter = pvc_Keyword != null ?
                new ObjectParameter("Pvc_Keyword", pvc_Keyword) :
                new ObjectParameter("Pvc_Keyword", typeof(string));
    
            var pvc_TypeParameter = pvc_Type != null ?
                new ObjectParameter("Pvc_Type", pvc_Type) :
                new ObjectParameter("Pvc_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_CPanel_ManageCompanyProfile_Form_Result>("Usp_Ezy_CPanel_ManageCompanyProfile_Form", pvc_KeyParameter, pvc_CTypeParameter, pvc_KeywordParameter, pvc_TypeParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_Txn_RetriveOrdHeadRef_Result> Usp_Ezy_Txn_RetriveOrdHeadRef(string pvc_TxnNumber, string pvc_Filter1, string pvc_Filter2, string pvc_Filter3, string pvc_Filter4, string pvc_Filter5, string pvc_Filter6, string pvc_Type)
        {
            var pvc_TxnNumberParameter = pvc_TxnNumber != null ?
                new ObjectParameter("Pvc_TxnNumber", pvc_TxnNumber) :
                new ObjectParameter("Pvc_TxnNumber", typeof(string));
    
            var pvc_Filter1Parameter = pvc_Filter1 != null ?
                new ObjectParameter("Pvc_Filter1", pvc_Filter1) :
                new ObjectParameter("Pvc_Filter1", typeof(string));
    
            var pvc_Filter2Parameter = pvc_Filter2 != null ?
                new ObjectParameter("Pvc_Filter2", pvc_Filter2) :
                new ObjectParameter("Pvc_Filter2", typeof(string));
    
            var pvc_Filter3Parameter = pvc_Filter3 != null ?
                new ObjectParameter("Pvc_Filter3", pvc_Filter3) :
                new ObjectParameter("Pvc_Filter3", typeof(string));
    
            var pvc_Filter4Parameter = pvc_Filter4 != null ?
                new ObjectParameter("Pvc_Filter4", pvc_Filter4) :
                new ObjectParameter("Pvc_Filter4", typeof(string));
    
            var pvc_Filter5Parameter = pvc_Filter5 != null ?
                new ObjectParameter("Pvc_Filter5", pvc_Filter5) :
                new ObjectParameter("Pvc_Filter5", typeof(string));
    
            var pvc_Filter6Parameter = pvc_Filter6 != null ?
                new ObjectParameter("Pvc_Filter6", pvc_Filter6) :
                new ObjectParameter("Pvc_Filter6", typeof(string));
    
            var pvc_TypeParameter = pvc_Type != null ?
                new ObjectParameter("Pvc_Type", pvc_Type) :
                new ObjectParameter("Pvc_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_Txn_RetriveOrdHeadRef_Result>("Usp_Ezy_Txn_RetriveOrdHeadRef", pvc_TxnNumberParameter, pvc_Filter1Parameter, pvc_Filter2Parameter, pvc_Filter3Parameter, pvc_Filter4Parameter, pvc_Filter5Parameter, pvc_Filter6Parameter, pvc_TypeParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_Txn_RetriveDebriefingFromData_Result> Usp_Ezy_Txn_RetriveDebriefingFromData(string pvc_TxnNumber, string pvc_Filter1, string pvc_Filter2, string pvc_Filter3, string pvc_Filter4, string pvc_Filter5, string pvc_Filter6, string pvc_Type)
        {
            var pvc_TxnNumberParameter = pvc_TxnNumber != null ?
                new ObjectParameter("Pvc_TxnNumber", pvc_TxnNumber) :
                new ObjectParameter("Pvc_TxnNumber", typeof(string));
    
            var pvc_Filter1Parameter = pvc_Filter1 != null ?
                new ObjectParameter("Pvc_Filter1", pvc_Filter1) :
                new ObjectParameter("Pvc_Filter1", typeof(string));
    
            var pvc_Filter2Parameter = pvc_Filter2 != null ?
                new ObjectParameter("Pvc_Filter2", pvc_Filter2) :
                new ObjectParameter("Pvc_Filter2", typeof(string));
    
            var pvc_Filter3Parameter = pvc_Filter3 != null ?
                new ObjectParameter("Pvc_Filter3", pvc_Filter3) :
                new ObjectParameter("Pvc_Filter3", typeof(string));
    
            var pvc_Filter4Parameter = pvc_Filter4 != null ?
                new ObjectParameter("Pvc_Filter4", pvc_Filter4) :
                new ObjectParameter("Pvc_Filter4", typeof(string));
    
            var pvc_Filter5Parameter = pvc_Filter5 != null ?
                new ObjectParameter("Pvc_Filter5", pvc_Filter5) :
                new ObjectParameter("Pvc_Filter5", typeof(string));
    
            var pvc_Filter6Parameter = pvc_Filter6 != null ?
                new ObjectParameter("Pvc_Filter6", pvc_Filter6) :
                new ObjectParameter("Pvc_Filter6", typeof(string));
    
            var pvc_TypeParameter = pvc_Type != null ?
                new ObjectParameter("Pvc_Type", pvc_Type) :
                new ObjectParameter("Pvc_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_Txn_RetriveDebriefingFromData_Result>("Usp_Ezy_Txn_RetriveDebriefingFromData", pvc_TxnNumberParameter, pvc_Filter1Parameter, pvc_Filter2Parameter, pvc_Filter3Parameter, pvc_Filter4Parameter, pvc_Filter5Parameter, pvc_Filter6Parameter, pvc_TypeParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_Txn_RetriveInvoiceList_Result> Usp_Ezy_Txn_RetriveInvoiceList(string pvc_TxnNumber, string pvc_Filter1, string pvc_Filter2, string pvc_Filter3, string pvc_Filter4, string pvc_Filter5, string pvc_Filter6, string pvc_Type)
        {
            var pvc_TxnNumberParameter = pvc_TxnNumber != null ?
                new ObjectParameter("Pvc_TxnNumber", pvc_TxnNumber) :
                new ObjectParameter("Pvc_TxnNumber", typeof(string));
    
            var pvc_Filter1Parameter = pvc_Filter1 != null ?
                new ObjectParameter("Pvc_Filter1", pvc_Filter1) :
                new ObjectParameter("Pvc_Filter1", typeof(string));
    
            var pvc_Filter2Parameter = pvc_Filter2 != null ?
                new ObjectParameter("Pvc_Filter2", pvc_Filter2) :
                new ObjectParameter("Pvc_Filter2", typeof(string));
    
            var pvc_Filter3Parameter = pvc_Filter3 != null ?
                new ObjectParameter("Pvc_Filter3", pvc_Filter3) :
                new ObjectParameter("Pvc_Filter3", typeof(string));
    
            var pvc_Filter4Parameter = pvc_Filter4 != null ?
                new ObjectParameter("Pvc_Filter4", pvc_Filter4) :
                new ObjectParameter("Pvc_Filter4", typeof(string));
    
            var pvc_Filter5Parameter = pvc_Filter5 != null ?
                new ObjectParameter("Pvc_Filter5", pvc_Filter5) :
                new ObjectParameter("Pvc_Filter5", typeof(string));
    
            var pvc_Filter6Parameter = pvc_Filter6 != null ?
                new ObjectParameter("Pvc_Filter6", pvc_Filter6) :
                new ObjectParameter("Pvc_Filter6", typeof(string));
    
            var pvc_TypeParameter = pvc_Type != null ?
                new ObjectParameter("Pvc_Type", pvc_Type) :
                new ObjectParameter("Pvc_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_Txn_RetriveInvoiceList_Result>("Usp_Ezy_Txn_RetriveInvoiceList", pvc_TxnNumberParameter, pvc_Filter1Parameter, pvc_Filter2Parameter, pvc_Filter3Parameter, pvc_Filter4Parameter, pvc_Filter5Parameter, pvc_Filter6Parameter, pvc_TypeParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_Txn_RetriveInvoiceForm_Result> Usp_Ezy_Txn_RetriveInvoiceForm(string pvc_TxnNumber, string pvc_Filter1, string pvc_Filter2, string pvc_Filter3, string pvc_Filter4, string pvc_Filter5, string pvc_Filter6, string pvc_Type)
        {
            var pvc_TxnNumberParameter = pvc_TxnNumber != null ?
                new ObjectParameter("Pvc_TxnNumber", pvc_TxnNumber) :
                new ObjectParameter("Pvc_TxnNumber", typeof(string));
    
            var pvc_Filter1Parameter = pvc_Filter1 != null ?
                new ObjectParameter("Pvc_Filter1", pvc_Filter1) :
                new ObjectParameter("Pvc_Filter1", typeof(string));
    
            var pvc_Filter2Parameter = pvc_Filter2 != null ?
                new ObjectParameter("Pvc_Filter2", pvc_Filter2) :
                new ObjectParameter("Pvc_Filter2", typeof(string));
    
            var pvc_Filter3Parameter = pvc_Filter3 != null ?
                new ObjectParameter("Pvc_Filter3", pvc_Filter3) :
                new ObjectParameter("Pvc_Filter3", typeof(string));
    
            var pvc_Filter4Parameter = pvc_Filter4 != null ?
                new ObjectParameter("Pvc_Filter4", pvc_Filter4) :
                new ObjectParameter("Pvc_Filter4", typeof(string));
    
            var pvc_Filter5Parameter = pvc_Filter5 != null ?
                new ObjectParameter("Pvc_Filter5", pvc_Filter5) :
                new ObjectParameter("Pvc_Filter5", typeof(string));
    
            var pvc_Filter6Parameter = pvc_Filter6 != null ?
                new ObjectParameter("Pvc_Filter6", pvc_Filter6) :
                new ObjectParameter("Pvc_Filter6", typeof(string));
    
            var pvc_TypeParameter = pvc_Type != null ?
                new ObjectParameter("Pvc_Type", pvc_Type) :
                new ObjectParameter("Pvc_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_Txn_RetriveInvoiceForm_Result>("Usp_Ezy_Txn_RetriveInvoiceForm", pvc_TxnNumberParameter, pvc_Filter1Parameter, pvc_Filter2Parameter, pvc_Filter3Parameter, pvc_Filter4Parameter, pvc_Filter5Parameter, pvc_Filter6Parameter, pvc_TypeParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_Txn_RetriveDashBoards_Result> Usp_Ezy_Txn_RetriveDashBoards(string pvc_TxnNumber, string pvc_Filter1, string pvc_Filter2, string pvc_Filter3, string pvc_Filter4, string pvc_Filter5, string pvc_Filter6, string pvc_Type)
        {
            var pvc_TxnNumberParameter = pvc_TxnNumber != null ?
                new ObjectParameter("Pvc_TxnNumber", pvc_TxnNumber) :
                new ObjectParameter("Pvc_TxnNumber", typeof(string));
    
            var pvc_Filter1Parameter = pvc_Filter1 != null ?
                new ObjectParameter("Pvc_Filter1", pvc_Filter1) :
                new ObjectParameter("Pvc_Filter1", typeof(string));
    
            var pvc_Filter2Parameter = pvc_Filter2 != null ?
                new ObjectParameter("Pvc_Filter2", pvc_Filter2) :
                new ObjectParameter("Pvc_Filter2", typeof(string));
    
            var pvc_Filter3Parameter = pvc_Filter3 != null ?
                new ObjectParameter("Pvc_Filter3", pvc_Filter3) :
                new ObjectParameter("Pvc_Filter3", typeof(string));
    
            var pvc_Filter4Parameter = pvc_Filter4 != null ?
                new ObjectParameter("Pvc_Filter4", pvc_Filter4) :
                new ObjectParameter("Pvc_Filter4", typeof(string));
    
            var pvc_Filter5Parameter = pvc_Filter5 != null ?
                new ObjectParameter("Pvc_Filter5", pvc_Filter5) :
                new ObjectParameter("Pvc_Filter5", typeof(string));
    
            var pvc_Filter6Parameter = pvc_Filter6 != null ?
                new ObjectParameter("Pvc_Filter6", pvc_Filter6) :
                new ObjectParameter("Pvc_Filter6", typeof(string));
    
            var pvc_TypeParameter = pvc_Type != null ?
                new ObjectParameter("Pvc_Type", pvc_Type) :
                new ObjectParameter("Pvc_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_Txn_RetriveDashBoards_Result>("Usp_Ezy_Txn_RetriveDashBoards", pvc_TxnNumberParameter, pvc_Filter1Parameter, pvc_Filter2Parameter, pvc_Filter3Parameter, pvc_Filter4Parameter, pvc_Filter5Parameter, pvc_Filter6Parameter, pvc_TypeParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_Txn_RetriveFolloupApprove_Result> Usp_Ezy_Txn_RetriveFolloupApprove(string pvc_TxnNumber, string pvc_Filter1, string pvc_Filter2, string pvc_Filter3, string pvc_Filter4, string pvc_Filter5, string pvc_Filter6, string pvc_Type)
        {
            var pvc_TxnNumberParameter = pvc_TxnNumber != null ?
                new ObjectParameter("Pvc_TxnNumber", pvc_TxnNumber) :
                new ObjectParameter("Pvc_TxnNumber", typeof(string));
    
            var pvc_Filter1Parameter = pvc_Filter1 != null ?
                new ObjectParameter("Pvc_Filter1", pvc_Filter1) :
                new ObjectParameter("Pvc_Filter1", typeof(string));
    
            var pvc_Filter2Parameter = pvc_Filter2 != null ?
                new ObjectParameter("Pvc_Filter2", pvc_Filter2) :
                new ObjectParameter("Pvc_Filter2", typeof(string));
    
            var pvc_Filter3Parameter = pvc_Filter3 != null ?
                new ObjectParameter("Pvc_Filter3", pvc_Filter3) :
                new ObjectParameter("Pvc_Filter3", typeof(string));
    
            var pvc_Filter4Parameter = pvc_Filter4 != null ?
                new ObjectParameter("Pvc_Filter4", pvc_Filter4) :
                new ObjectParameter("Pvc_Filter4", typeof(string));
    
            var pvc_Filter5Parameter = pvc_Filter5 != null ?
                new ObjectParameter("Pvc_Filter5", pvc_Filter5) :
                new ObjectParameter("Pvc_Filter5", typeof(string));
    
            var pvc_Filter6Parameter = pvc_Filter6 != null ?
                new ObjectParameter("Pvc_Filter6", pvc_Filter6) :
                new ObjectParameter("Pvc_Filter6", typeof(string));
    
            var pvc_TypeParameter = pvc_Type != null ?
                new ObjectParameter("Pvc_Type", pvc_Type) :
                new ObjectParameter("Pvc_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_Txn_RetriveFolloupApprove_Result>("Usp_Ezy_Txn_RetriveFolloupApprove", pvc_TxnNumberParameter, pvc_Filter1Parameter, pvc_Filter2Parameter, pvc_Filter3Parameter, pvc_Filter4Parameter, pvc_Filter5Parameter, pvc_Filter6Parameter, pvc_TypeParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_Txn_RetriveTxnPendingOrderData_Result> Usp_Ezy_Txn_RetriveTxnPendingOrderData(string pvc_TxnNumber, string pvc_Filter1, string pvc_Filter2, string pvc_Filter3, string pvc_Filter4, string pvc_Filter5, string pvc_Filter6, string pvc_Type)
        {
            var pvc_TxnNumberParameter = pvc_TxnNumber != null ?
                new ObjectParameter("Pvc_TxnNumber", pvc_TxnNumber) :
                new ObjectParameter("Pvc_TxnNumber", typeof(string));
    
            var pvc_Filter1Parameter = pvc_Filter1 != null ?
                new ObjectParameter("Pvc_Filter1", pvc_Filter1) :
                new ObjectParameter("Pvc_Filter1", typeof(string));
    
            var pvc_Filter2Parameter = pvc_Filter2 != null ?
                new ObjectParameter("Pvc_Filter2", pvc_Filter2) :
                new ObjectParameter("Pvc_Filter2", typeof(string));
    
            var pvc_Filter3Parameter = pvc_Filter3 != null ?
                new ObjectParameter("Pvc_Filter3", pvc_Filter3) :
                new ObjectParameter("Pvc_Filter3", typeof(string));
    
            var pvc_Filter4Parameter = pvc_Filter4 != null ?
                new ObjectParameter("Pvc_Filter4", pvc_Filter4) :
                new ObjectParameter("Pvc_Filter4", typeof(string));
    
            var pvc_Filter5Parameter = pvc_Filter5 != null ?
                new ObjectParameter("Pvc_Filter5", pvc_Filter5) :
                new ObjectParameter("Pvc_Filter5", typeof(string));
    
            var pvc_Filter6Parameter = pvc_Filter6 != null ?
                new ObjectParameter("Pvc_Filter6", pvc_Filter6) :
                new ObjectParameter("Pvc_Filter6", typeof(string));
    
            var pvc_TypeParameter = pvc_Type != null ?
                new ObjectParameter("Pvc_Type", pvc_Type) :
                new ObjectParameter("Pvc_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_Txn_RetriveTxnPendingOrderData_Result>("Usp_Ezy_Txn_RetriveTxnPendingOrderData", pvc_TxnNumberParameter, pvc_Filter1Parameter, pvc_Filter2Parameter, pvc_Filter3Parameter, pvc_Filter4Parameter, pvc_Filter5Parameter, pvc_Filter6Parameter, pvc_TypeParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_Txn_RetriveTxnPendingOrderFormData_Result> Usp_Ezy_Txn_RetriveTxnPendingOrderFormData(string pvc_TxnNumber, string pvc_Filter1, string pvc_Filter2, string pvc_Filter3, string pvc_Filter4, string pvc_Filter5, string pvc_Filter6, string pvc_Type)
        {
            var pvc_TxnNumberParameter = pvc_TxnNumber != null ?
                new ObjectParameter("Pvc_TxnNumber", pvc_TxnNumber) :
                new ObjectParameter("Pvc_TxnNumber", typeof(string));
    
            var pvc_Filter1Parameter = pvc_Filter1 != null ?
                new ObjectParameter("Pvc_Filter1", pvc_Filter1) :
                new ObjectParameter("Pvc_Filter1", typeof(string));
    
            var pvc_Filter2Parameter = pvc_Filter2 != null ?
                new ObjectParameter("Pvc_Filter2", pvc_Filter2) :
                new ObjectParameter("Pvc_Filter2", typeof(string));
    
            var pvc_Filter3Parameter = pvc_Filter3 != null ?
                new ObjectParameter("Pvc_Filter3", pvc_Filter3) :
                new ObjectParameter("Pvc_Filter3", typeof(string));
    
            var pvc_Filter4Parameter = pvc_Filter4 != null ?
                new ObjectParameter("Pvc_Filter4", pvc_Filter4) :
                new ObjectParameter("Pvc_Filter4", typeof(string));
    
            var pvc_Filter5Parameter = pvc_Filter5 != null ?
                new ObjectParameter("Pvc_Filter5", pvc_Filter5) :
                new ObjectParameter("Pvc_Filter5", typeof(string));
    
            var pvc_Filter6Parameter = pvc_Filter6 != null ?
                new ObjectParameter("Pvc_Filter6", pvc_Filter6) :
                new ObjectParameter("Pvc_Filter6", typeof(string));
    
            var pvc_TypeParameter = pvc_Type != null ?
                new ObjectParameter("Pvc_Type", pvc_Type) :
                new ObjectParameter("Pvc_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_Txn_RetriveTxnPendingOrderFormData_Result>("Usp_Ezy_Txn_RetriveTxnPendingOrderFormData", pvc_TxnNumberParameter, pvc_Filter1Parameter, pvc_Filter2Parameter, pvc_Filter3Parameter, pvc_Filter4Parameter, pvc_Filter5Parameter, pvc_Filter6Parameter, pvc_TypeParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_Txn_RetrivePendingFolloupList_Result> Usp_Ezy_Txn_RetrivePendingFolloupList(string pvc_TxnNumber, string pvc_Filter1, string pvc_Filter2, string pvc_Filter3, string pvc_Filter4, string pvc_Filter5, string pvc_Filter6, string pvc_Type)
        {
            var pvc_TxnNumberParameter = pvc_TxnNumber != null ?
                new ObjectParameter("Pvc_TxnNumber", pvc_TxnNumber) :
                new ObjectParameter("Pvc_TxnNumber", typeof(string));
    
            var pvc_Filter1Parameter = pvc_Filter1 != null ?
                new ObjectParameter("Pvc_Filter1", pvc_Filter1) :
                new ObjectParameter("Pvc_Filter1", typeof(string));
    
            var pvc_Filter2Parameter = pvc_Filter2 != null ?
                new ObjectParameter("Pvc_Filter2", pvc_Filter2) :
                new ObjectParameter("Pvc_Filter2", typeof(string));
    
            var pvc_Filter3Parameter = pvc_Filter3 != null ?
                new ObjectParameter("Pvc_Filter3", pvc_Filter3) :
                new ObjectParameter("Pvc_Filter3", typeof(string));
    
            var pvc_Filter4Parameter = pvc_Filter4 != null ?
                new ObjectParameter("Pvc_Filter4", pvc_Filter4) :
                new ObjectParameter("Pvc_Filter4", typeof(string));
    
            var pvc_Filter5Parameter = pvc_Filter5 != null ?
                new ObjectParameter("Pvc_Filter5", pvc_Filter5) :
                new ObjectParameter("Pvc_Filter5", typeof(string));
    
            var pvc_Filter6Parameter = pvc_Filter6 != null ?
                new ObjectParameter("Pvc_Filter6", pvc_Filter6) :
                new ObjectParameter("Pvc_Filter6", typeof(string));
    
            var pvc_TypeParameter = pvc_Type != null ?
                new ObjectParameter("Pvc_Type", pvc_Type) :
                new ObjectParameter("Pvc_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_Txn_RetrivePendingFolloupList_Result>("Usp_Ezy_Txn_RetrivePendingFolloupList", pvc_TxnNumberParameter, pvc_Filter1Parameter, pvc_Filter2Parameter, pvc_Filter3Parameter, pvc_Filter4Parameter, pvc_Filter5Parameter, pvc_Filter6Parameter, pvc_TypeParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_Txn_RetrivepENDINGFolloupFormData_Result> Usp_Ezy_Txn_RetrivepENDINGFolloupFormData(string pvc_TxnNumber, string pvc_Filter1, string pvc_Filter2, string pvc_Filter3, string pvc_Filter4, string pvc_Filter5, string pvc_Filter6, string pvc_Type)
        {
            var pvc_TxnNumberParameter = pvc_TxnNumber != null ?
                new ObjectParameter("Pvc_TxnNumber", pvc_TxnNumber) :
                new ObjectParameter("Pvc_TxnNumber", typeof(string));
    
            var pvc_Filter1Parameter = pvc_Filter1 != null ?
                new ObjectParameter("Pvc_Filter1", pvc_Filter1) :
                new ObjectParameter("Pvc_Filter1", typeof(string));
    
            var pvc_Filter2Parameter = pvc_Filter2 != null ?
                new ObjectParameter("Pvc_Filter2", pvc_Filter2) :
                new ObjectParameter("Pvc_Filter2", typeof(string));
    
            var pvc_Filter3Parameter = pvc_Filter3 != null ?
                new ObjectParameter("Pvc_Filter3", pvc_Filter3) :
                new ObjectParameter("Pvc_Filter3", typeof(string));
    
            var pvc_Filter4Parameter = pvc_Filter4 != null ?
                new ObjectParameter("Pvc_Filter4", pvc_Filter4) :
                new ObjectParameter("Pvc_Filter4", typeof(string));
    
            var pvc_Filter5Parameter = pvc_Filter5 != null ?
                new ObjectParameter("Pvc_Filter5", pvc_Filter5) :
                new ObjectParameter("Pvc_Filter5", typeof(string));
    
            var pvc_Filter6Parameter = pvc_Filter6 != null ?
                new ObjectParameter("Pvc_Filter6", pvc_Filter6) :
                new ObjectParameter("Pvc_Filter6", typeof(string));
    
            var pvc_TypeParameter = pvc_Type != null ?
                new ObjectParameter("Pvc_Type", pvc_Type) :
                new ObjectParameter("Pvc_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_Txn_RetrivepENDINGFolloupFormData_Result>("Usp_Ezy_Txn_RetrivepENDINGFolloupFormData", pvc_TxnNumberParameter, pvc_Filter1Parameter, pvc_Filter2Parameter, pvc_Filter3Parameter, pvc_Filter4Parameter, pvc_Filter5Parameter, pvc_Filter6Parameter, pvc_TypeParameter);
        }
    
        public virtual int Usp_Ezy_Common_Cancel(string pvc_Key, string pvc_Filter1, string pvc_Filter2, string pvc_Filter3, string pvc_Filter4, string pvc_MasterType)
        {
            var pvc_KeyParameter = pvc_Key != null ?
                new ObjectParameter("Pvc_Key", pvc_Key) :
                new ObjectParameter("Pvc_Key", typeof(string));
    
            var pvc_Filter1Parameter = pvc_Filter1 != null ?
                new ObjectParameter("Pvc_Filter1", pvc_Filter1) :
                new ObjectParameter("Pvc_Filter1", typeof(string));
    
            var pvc_Filter2Parameter = pvc_Filter2 != null ?
                new ObjectParameter("Pvc_Filter2", pvc_Filter2) :
                new ObjectParameter("Pvc_Filter2", typeof(string));
    
            var pvc_Filter3Parameter = pvc_Filter3 != null ?
                new ObjectParameter("Pvc_Filter3", pvc_Filter3) :
                new ObjectParameter("Pvc_Filter3", typeof(string));
    
            var pvc_Filter4Parameter = pvc_Filter4 != null ?
                new ObjectParameter("Pvc_Filter4", pvc_Filter4) :
                new ObjectParameter("Pvc_Filter4", typeof(string));
    
            var pvc_MasterTypeParameter = pvc_MasterType != null ?
                new ObjectParameter("Pvc_MasterType", pvc_MasterType) :
                new ObjectParameter("Pvc_MasterType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Usp_Ezy_Common_Cancel", pvc_KeyParameter, pvc_Filter1Parameter, pvc_Filter2Parameter, pvc_Filter3Parameter, pvc_Filter4Parameter, pvc_MasterTypeParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_Txn_RetriveViewData_Result> Usp_Ezy_Txn_RetriveViewData(string pvc_Key, string pvc_Filter1, string pvc_Filter2, string pvc_Filter3, string pvc_Filter4, string pvc_Type)
        {
            var pvc_KeyParameter = pvc_Key != null ?
                new ObjectParameter("Pvc_Key", pvc_Key) :
                new ObjectParameter("Pvc_Key", typeof(string));
    
            var pvc_Filter1Parameter = pvc_Filter1 != null ?
                new ObjectParameter("Pvc_Filter1", pvc_Filter1) :
                new ObjectParameter("Pvc_Filter1", typeof(string));
    
            var pvc_Filter2Parameter = pvc_Filter2 != null ?
                new ObjectParameter("Pvc_Filter2", pvc_Filter2) :
                new ObjectParameter("Pvc_Filter2", typeof(string));
    
            var pvc_Filter3Parameter = pvc_Filter3 != null ?
                new ObjectParameter("Pvc_Filter3", pvc_Filter3) :
                new ObjectParameter("Pvc_Filter3", typeof(string));
    
            var pvc_Filter4Parameter = pvc_Filter4 != null ?
                new ObjectParameter("Pvc_Filter4", pvc_Filter4) :
                new ObjectParameter("Pvc_Filter4", typeof(string));
    
            var pvc_TypeParameter = pvc_Type != null ?
                new ObjectParameter("Pvc_Type", pvc_Type) :
                new ObjectParameter("Pvc_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_Txn_RetriveViewData_Result>("Usp_Ezy_Txn_RetriveViewData", pvc_KeyParameter, pvc_Filter1Parameter, pvc_Filter2Parameter, pvc_Filter3Parameter, pvc_Filter4Parameter, pvc_TypeParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_Txn_RetriveViewFormData_Result> Usp_Ezy_Txn_RetriveViewFormData(string pvc_Key, string pvc_Filter1, string pvc_Filter2, string pvc_Filter3, string pvc_Filter4, string pvc_Type)
        {
            var pvc_KeyParameter = pvc_Key != null ?
                new ObjectParameter("Pvc_Key", pvc_Key) :
                new ObjectParameter("Pvc_Key", typeof(string));
    
            var pvc_Filter1Parameter = pvc_Filter1 != null ?
                new ObjectParameter("Pvc_Filter1", pvc_Filter1) :
                new ObjectParameter("Pvc_Filter1", typeof(string));
    
            var pvc_Filter2Parameter = pvc_Filter2 != null ?
                new ObjectParameter("Pvc_Filter2", pvc_Filter2) :
                new ObjectParameter("Pvc_Filter2", typeof(string));
    
            var pvc_Filter3Parameter = pvc_Filter3 != null ?
                new ObjectParameter("Pvc_Filter3", pvc_Filter3) :
                new ObjectParameter("Pvc_Filter3", typeof(string));
    
            var pvc_Filter4Parameter = pvc_Filter4 != null ?
                new ObjectParameter("Pvc_Filter4", pvc_Filter4) :
                new ObjectParameter("Pvc_Filter4", typeof(string));
    
            var pvc_TypeParameter = pvc_Type != null ?
                new ObjectParameter("Pvc_Type", pvc_Type) :
                new ObjectParameter("Pvc_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_Txn_RetriveViewFormData_Result>("Usp_Ezy_Txn_RetriveViewFormData", pvc_KeyParameter, pvc_Filter1Parameter, pvc_Filter2Parameter, pvc_Filter3Parameter, pvc_Filter4Parameter, pvc_TypeParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_Txn_RetriveCS_APNData_Result> Usp_Ezy_Txn_RetriveCS_APNData(string pvc_TxnNumber, string pvc_Filter1, string pvc_Filter2, string pvc_Filter3, string pvc_Filter4, string pvc_Filter5, string pvc_Filter6, string pvc_Type)
        {
            var pvc_TxnNumberParameter = pvc_TxnNumber != null ?
                new ObjectParameter("Pvc_TxnNumber", pvc_TxnNumber) :
                new ObjectParameter("Pvc_TxnNumber", typeof(string));
    
            var pvc_Filter1Parameter = pvc_Filter1 != null ?
                new ObjectParameter("Pvc_Filter1", pvc_Filter1) :
                new ObjectParameter("Pvc_Filter1", typeof(string));
    
            var pvc_Filter2Parameter = pvc_Filter2 != null ?
                new ObjectParameter("Pvc_Filter2", pvc_Filter2) :
                new ObjectParameter("Pvc_Filter2", typeof(string));
    
            var pvc_Filter3Parameter = pvc_Filter3 != null ?
                new ObjectParameter("Pvc_Filter3", pvc_Filter3) :
                new ObjectParameter("Pvc_Filter3", typeof(string));
    
            var pvc_Filter4Parameter = pvc_Filter4 != null ?
                new ObjectParameter("Pvc_Filter4", pvc_Filter4) :
                new ObjectParameter("Pvc_Filter4", typeof(string));
    
            var pvc_Filter5Parameter = pvc_Filter5 != null ?
                new ObjectParameter("Pvc_Filter5", pvc_Filter5) :
                new ObjectParameter("Pvc_Filter5", typeof(string));
    
            var pvc_Filter6Parameter = pvc_Filter6 != null ?
                new ObjectParameter("Pvc_Filter6", pvc_Filter6) :
                new ObjectParameter("Pvc_Filter6", typeof(string));
    
            var pvc_TypeParameter = pvc_Type != null ?
                new ObjectParameter("Pvc_Type", pvc_Type) :
                new ObjectParameter("Pvc_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_Txn_RetriveCS_APNData_Result>("Usp_Ezy_Txn_RetriveCS_APNData", pvc_TxnNumberParameter, pvc_Filter1Parameter, pvc_Filter2Parameter, pvc_Filter3Parameter, pvc_Filter4Parameter, pvc_Filter5Parameter, pvc_Filter6Parameter, pvc_TypeParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_Txn_RetriveCS_APN_FormData_Result> Usp_Ezy_Txn_RetriveCS_APN_FormData(string pvc_TxnNumber, string pvc_Filter1, string pvc_Filter2, string pvc_Filter3, string pvc_Filter4, string pvc_Filter5, string pvc_Filter6, string pvc_Type)
        {
            var pvc_TxnNumberParameter = pvc_TxnNumber != null ?
                new ObjectParameter("Pvc_TxnNumber", pvc_TxnNumber) :
                new ObjectParameter("Pvc_TxnNumber", typeof(string));
    
            var pvc_Filter1Parameter = pvc_Filter1 != null ?
                new ObjectParameter("Pvc_Filter1", pvc_Filter1) :
                new ObjectParameter("Pvc_Filter1", typeof(string));
    
            var pvc_Filter2Parameter = pvc_Filter2 != null ?
                new ObjectParameter("Pvc_Filter2", pvc_Filter2) :
                new ObjectParameter("Pvc_Filter2", typeof(string));
    
            var pvc_Filter3Parameter = pvc_Filter3 != null ?
                new ObjectParameter("Pvc_Filter3", pvc_Filter3) :
                new ObjectParameter("Pvc_Filter3", typeof(string));
    
            var pvc_Filter4Parameter = pvc_Filter4 != null ?
                new ObjectParameter("Pvc_Filter4", pvc_Filter4) :
                new ObjectParameter("Pvc_Filter4", typeof(string));
    
            var pvc_Filter5Parameter = pvc_Filter5 != null ?
                new ObjectParameter("Pvc_Filter5", pvc_Filter5) :
                new ObjectParameter("Pvc_Filter5", typeof(string));
    
            var pvc_Filter6Parameter = pvc_Filter6 != null ?
                new ObjectParameter("Pvc_Filter6", pvc_Filter6) :
                new ObjectParameter("Pvc_Filter6", typeof(string));
    
            var pvc_TypeParameter = pvc_Type != null ?
                new ObjectParameter("Pvc_Type", pvc_Type) :
                new ObjectParameter("Pvc_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_Txn_RetriveCS_APN_FormData_Result>("Usp_Ezy_Txn_RetriveCS_APN_FormData", pvc_TxnNumberParameter, pvc_Filter1Parameter, pvc_Filter2Parameter, pvc_Filter3Parameter, pvc_Filter4Parameter, pvc_Filter5Parameter, pvc_Filter6Parameter, pvc_TypeParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_Txn_RetriveTxnData_OrderDetailsView_Result> Usp_Ezy_Txn_RetriveTxnData_OrderDetailsView(string pvc_TxnNumber, string pvc_Filter1, string pvc_Filter2, string pvc_Filter3, string pvc_Filter4, string pvc_Filter5, string pvc_Filter6, string pvc_Type)
        {
            var pvc_TxnNumberParameter = pvc_TxnNumber != null ?
                new ObjectParameter("Pvc_TxnNumber", pvc_TxnNumber) :
                new ObjectParameter("Pvc_TxnNumber", typeof(string));
    
            var pvc_Filter1Parameter = pvc_Filter1 != null ?
                new ObjectParameter("Pvc_Filter1", pvc_Filter1) :
                new ObjectParameter("Pvc_Filter1", typeof(string));
    
            var pvc_Filter2Parameter = pvc_Filter2 != null ?
                new ObjectParameter("Pvc_Filter2", pvc_Filter2) :
                new ObjectParameter("Pvc_Filter2", typeof(string));
    
            var pvc_Filter3Parameter = pvc_Filter3 != null ?
                new ObjectParameter("Pvc_Filter3", pvc_Filter3) :
                new ObjectParameter("Pvc_Filter3", typeof(string));
    
            var pvc_Filter4Parameter = pvc_Filter4 != null ?
                new ObjectParameter("Pvc_Filter4", pvc_Filter4) :
                new ObjectParameter("Pvc_Filter4", typeof(string));
    
            var pvc_Filter5Parameter = pvc_Filter5 != null ?
                new ObjectParameter("Pvc_Filter5", pvc_Filter5) :
                new ObjectParameter("Pvc_Filter5", typeof(string));
    
            var pvc_Filter6Parameter = pvc_Filter6 != null ?
                new ObjectParameter("Pvc_Filter6", pvc_Filter6) :
                new ObjectParameter("Pvc_Filter6", typeof(string));
    
            var pvc_TypeParameter = pvc_Type != null ?
                new ObjectParameter("Pvc_Type", pvc_Type) :
                new ObjectParameter("Pvc_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_Txn_RetriveTxnData_OrderDetailsView_Result>("Usp_Ezy_Txn_RetriveTxnData_OrderDetailsView", pvc_TxnNumberParameter, pvc_Filter1Parameter, pvc_Filter2Parameter, pvc_Filter3Parameter, pvc_Filter4Parameter, pvc_Filter5Parameter, pvc_Filter6Parameter, pvc_TypeParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_Txn_RetriveViewData_BilledPartDetails_Result> Usp_Ezy_Txn_RetriveViewData_BilledPartDetails(string pvc_Key, string pvc_Filter1, string pvc_Filter2, string pvc_Filter3, string pvc_Filter4, string pvc_Type)
        {
            var pvc_KeyParameter = pvc_Key != null ?
                new ObjectParameter("Pvc_Key", pvc_Key) :
                new ObjectParameter("Pvc_Key", typeof(string));
    
            var pvc_Filter1Parameter = pvc_Filter1 != null ?
                new ObjectParameter("Pvc_Filter1", pvc_Filter1) :
                new ObjectParameter("Pvc_Filter1", typeof(string));
    
            var pvc_Filter2Parameter = pvc_Filter2 != null ?
                new ObjectParameter("Pvc_Filter2", pvc_Filter2) :
                new ObjectParameter("Pvc_Filter2", typeof(string));
    
            var pvc_Filter3Parameter = pvc_Filter3 != null ?
                new ObjectParameter("Pvc_Filter3", pvc_Filter3) :
                new ObjectParameter("Pvc_Filter3", typeof(string));
    
            var pvc_Filter4Parameter = pvc_Filter4 != null ?
                new ObjectParameter("Pvc_Filter4", pvc_Filter4) :
                new ObjectParameter("Pvc_Filter4", typeof(string));
    
            var pvc_TypeParameter = pvc_Type != null ?
                new ObjectParameter("Pvc_Type", pvc_Type) :
                new ObjectParameter("Pvc_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_Txn_RetriveViewData_BilledPartDetails_Result>("Usp_Ezy_Txn_RetriveViewData_BilledPartDetails", pvc_KeyParameter, pvc_Filter1Parameter, pvc_Filter2Parameter, pvc_Filter3Parameter, pvc_Filter4Parameter, pvc_TypeParameter);
        }
    
        public virtual ObjectResult<string> Usp_Ezy_Followup_Ref_update(string ord_followup_no, string ord_followup_amdno, string ord_followup_stage, string ord_followup_ref_id, string ord_ref_text, Nullable<System.DateTime> ord_ref_date)
        {
            var ord_followup_noParameter = ord_followup_no != null ?
                new ObjectParameter("ord_followup_no", ord_followup_no) :
                new ObjectParameter("ord_followup_no", typeof(string));
    
            var ord_followup_amdnoParameter = ord_followup_amdno != null ?
                new ObjectParameter("ord_followup_amdno", ord_followup_amdno) :
                new ObjectParameter("ord_followup_amdno", typeof(string));
    
            var ord_followup_stageParameter = ord_followup_stage != null ?
                new ObjectParameter("ord_followup_stage", ord_followup_stage) :
                new ObjectParameter("ord_followup_stage", typeof(string));
    
            var ord_followup_ref_idParameter = ord_followup_ref_id != null ?
                new ObjectParameter("ord_followup_ref_id", ord_followup_ref_id) :
                new ObjectParameter("ord_followup_ref_id", typeof(string));
    
            var ord_ref_textParameter = ord_ref_text != null ?
                new ObjectParameter("ord_ref_text", ord_ref_text) :
                new ObjectParameter("ord_ref_text", typeof(string));
    
            var ord_ref_dateParameter = ord_ref_date.HasValue ?
                new ObjectParameter("ord_ref_date", ord_ref_date) :
                new ObjectParameter("ord_ref_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Usp_Ezy_Followup_Ref_update", ord_followup_noParameter, ord_followup_amdnoParameter, ord_followup_stageParameter, ord_followup_ref_idParameter, ord_ref_textParameter, ord_ref_dateParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_Txn_RetriveViewData_AuditLog_Result_Result> Usp_Ezy_Txn_RetriveViewData_AuditLog_Result(string pvc_Key, string pvc_Filter1, string pvc_Filter2, string pvc_Filter3, string pvc_Filter4, string pvc_Type)
        {
            var pvc_KeyParameter = pvc_Key != null ?
                new ObjectParameter("Pvc_Key", pvc_Key) :
                new ObjectParameter("Pvc_Key", typeof(string));
    
            var pvc_Filter1Parameter = pvc_Filter1 != null ?
                new ObjectParameter("Pvc_Filter1", pvc_Filter1) :
                new ObjectParameter("Pvc_Filter1", typeof(string));
    
            var pvc_Filter2Parameter = pvc_Filter2 != null ?
                new ObjectParameter("Pvc_Filter2", pvc_Filter2) :
                new ObjectParameter("Pvc_Filter2", typeof(string));
    
            var pvc_Filter3Parameter = pvc_Filter3 != null ?
                new ObjectParameter("Pvc_Filter3", pvc_Filter3) :
                new ObjectParameter("Pvc_Filter3", typeof(string));
    
            var pvc_Filter4Parameter = pvc_Filter4 != null ?
                new ObjectParameter("Pvc_Filter4", pvc_Filter4) :
                new ObjectParameter("Pvc_Filter4", typeof(string));
    
            var pvc_TypeParameter = pvc_Type != null ?
                new ObjectParameter("Pvc_Type", pvc_Type) :
                new ObjectParameter("Pvc_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_Txn_RetriveViewData_AuditLog_Result_Result>("Usp_Ezy_Txn_RetriveViewData_AuditLog_Result", pvc_KeyParameter, pvc_Filter1Parameter, pvc_Filter2Parameter, pvc_Filter3Parameter, pvc_Filter4Parameter, pvc_TypeParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_Txn_UpdateDeviationOrder_Result> Usp_Ezy_Txn_UpdateDeviationOrder_If_OH_WP(string pvc_TxnNumber, string pvc_AmdNo, string pvc_Type)
        {
            var pvc_TxnNumberParameter = pvc_TxnNumber != null ?
                new ObjectParameter("Pvc_TxnNumber", pvc_TxnNumber) :
                new ObjectParameter("Pvc_TxnNumber", typeof(string));
    
            var pvc_AmdNoParameter = pvc_AmdNo != null ?
                new ObjectParameter("Pvc_AmdNo", pvc_AmdNo) :
                new ObjectParameter("Pvc_AmdNo", typeof(string));
    
            var pvc_TypeParameter = pvc_Type != null ?
                new ObjectParameter("Pvc_Type", pvc_Type) :
                new ObjectParameter("Pvc_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_Txn_UpdateDeviationOrder_Result>("Usp_Ezy_Txn_UpdateDeviationOrder_If_OH_WP", pvc_TxnNumberParameter, pvc_AmdNoParameter, pvc_TypeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Usp_Ezy_Txn_SRValidation(string pvc_SR)
        {
            var pvc_SRParameter = pvc_SR != null ?
                new ObjectParameter("Pvc_SR", pvc_SR) :
                new ObjectParameter("Pvc_SR", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Usp_Ezy_Txn_SRValidation", pvc_SRParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_Txn_SRValidation_Result> Usp_Ezy_Txn_SRValidation_SRCheck(string pvc_SR)
        {
            var pvc_SRParameter = pvc_SR != null ?
                new ObjectParameter("Pvc_SR", pvc_SR) :
                new ObjectParameter("Pvc_SR", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_Txn_SRValidation_Result>("Usp_Ezy_Txn_SRValidation_SRCheck", pvc_SRParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_Txn_Validation_Result1> Usp_Ezy_Txn_Validation(string pvc_Type, string pvc_Key, string pvc_Filter1, string pvc_Filter2, string pvc_Filter3)
        {
            var pvc_TypeParameter = pvc_Type != null ?
                new ObjectParameter("Pvc_Type", pvc_Type) :
                new ObjectParameter("Pvc_Type", typeof(string));
    
            var pvc_KeyParameter = pvc_Key != null ?
                new ObjectParameter("Pvc_Key", pvc_Key) :
                new ObjectParameter("Pvc_Key", typeof(string));
    
            var pvc_Filter1Parameter = pvc_Filter1 != null ?
                new ObjectParameter("Pvc_Filter1", pvc_Filter1) :
                new ObjectParameter("Pvc_Filter1", typeof(string));
    
            var pvc_Filter2Parameter = pvc_Filter2 != null ?
                new ObjectParameter("Pvc_Filter2", pvc_Filter2) :
                new ObjectParameter("Pvc_Filter2", typeof(string));
    
            var pvc_Filter3Parameter = pvc_Filter3 != null ?
                new ObjectParameter("Pvc_Filter3", pvc_Filter3) :
                new ObjectParameter("Pvc_Filter3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_Txn_Validation_Result1>("Usp_Ezy_Txn_Validation", pvc_TypeParameter, pvc_KeyParameter, pvc_Filter1Parameter, pvc_Filter2Parameter, pvc_Filter3Parameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_Common_RetriveMasterMCatHeader_Result> Usp_Ezy_Common_RetriveMasterMCatHeader(string pvc_Key, string pvc_Filter1, string pvc_Filter2, string pvc_Filter3, string pvc_Filter4, string pvc_MasterType)
        {
            var pvc_KeyParameter = pvc_Key != null ?
                new ObjectParameter("Pvc_Key", pvc_Key) :
                new ObjectParameter("Pvc_Key", typeof(string));
    
            var pvc_Filter1Parameter = pvc_Filter1 != null ?
                new ObjectParameter("Pvc_Filter1", pvc_Filter1) :
                new ObjectParameter("Pvc_Filter1", typeof(string));
    
            var pvc_Filter2Parameter = pvc_Filter2 != null ?
                new ObjectParameter("Pvc_Filter2", pvc_Filter2) :
                new ObjectParameter("Pvc_Filter2", typeof(string));
    
            var pvc_Filter3Parameter = pvc_Filter3 != null ?
                new ObjectParameter("Pvc_Filter3", pvc_Filter3) :
                new ObjectParameter("Pvc_Filter3", typeof(string));
    
            var pvc_Filter4Parameter = pvc_Filter4 != null ?
                new ObjectParameter("Pvc_Filter4", pvc_Filter4) :
                new ObjectParameter("Pvc_Filter4", typeof(string));
    
            var pvc_MasterTypeParameter = pvc_MasterType != null ?
                new ObjectParameter("Pvc_MasterType", pvc_MasterType) :
                new ObjectParameter("Pvc_MasterType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_Common_RetriveMasterMCatHeader_Result>("Usp_Ezy_Common_RetriveMasterMCatHeader", pvc_KeyParameter, pvc_Filter1Parameter, pvc_Filter2Parameter, pvc_Filter3Parameter, pvc_Filter4Parameter, pvc_MasterTypeParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_Common_ConfirmAndDeleteBan_Result> Usp_Ezy_Common_ConfirmAndDeleteBan(string pvc_Key1, string pvc_Key2, string pvc_Key3, string pvc_Action, string pvc_Type, string pvc_MasterType)
        {
            var pvc_Key1Parameter = pvc_Key1 != null ?
                new ObjectParameter("Pvc_Key1", pvc_Key1) :
                new ObjectParameter("Pvc_Key1", typeof(string));
    
            var pvc_Key2Parameter = pvc_Key2 != null ?
                new ObjectParameter("Pvc_Key2", pvc_Key2) :
                new ObjectParameter("Pvc_Key2", typeof(string));
    
            var pvc_Key3Parameter = pvc_Key3 != null ?
                new ObjectParameter("Pvc_Key3", pvc_Key3) :
                new ObjectParameter("Pvc_Key3", typeof(string));
    
            var pvc_ActionParameter = pvc_Action != null ?
                new ObjectParameter("Pvc_Action", pvc_Action) :
                new ObjectParameter("Pvc_Action", typeof(string));
    
            var pvc_TypeParameter = pvc_Type != null ?
                new ObjectParameter("Pvc_Type", pvc_Type) :
                new ObjectParameter("Pvc_Type", typeof(string));
    
            var pvc_MasterTypeParameter = pvc_MasterType != null ?
                new ObjectParameter("Pvc_MasterType", pvc_MasterType) :
                new ObjectParameter("Pvc_MasterType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_Common_ConfirmAndDeleteBan_Result>("Usp_Ezy_Common_ConfirmAndDeleteBan", pvc_Key1Parameter, pvc_Key2Parameter, pvc_Key3Parameter, pvc_ActionParameter, pvc_TypeParameter, pvc_MasterTypeParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_Txn_RetriveTxnData_Alt_Result> Usp_Ezy_Txn_RetriveTxnData_Alt(string pvc_TxnNumber, string pvc_Filter1, string pvc_Filter2, string pvc_Filter3, string pvc_Filter4, string pvc_Filter5, string pvc_Filter6, string pvc_Type)
        {
            var pvc_TxnNumberParameter = pvc_TxnNumber != null ?
                new ObjectParameter("Pvc_TxnNumber", pvc_TxnNumber) :
                new ObjectParameter("Pvc_TxnNumber", typeof(string));
    
            var pvc_Filter1Parameter = pvc_Filter1 != null ?
                new ObjectParameter("Pvc_Filter1", pvc_Filter1) :
                new ObjectParameter("Pvc_Filter1", typeof(string));
    
            var pvc_Filter2Parameter = pvc_Filter2 != null ?
                new ObjectParameter("Pvc_Filter2", pvc_Filter2) :
                new ObjectParameter("Pvc_Filter2", typeof(string));
    
            var pvc_Filter3Parameter = pvc_Filter3 != null ?
                new ObjectParameter("Pvc_Filter3", pvc_Filter3) :
                new ObjectParameter("Pvc_Filter3", typeof(string));
    
            var pvc_Filter4Parameter = pvc_Filter4 != null ?
                new ObjectParameter("Pvc_Filter4", pvc_Filter4) :
                new ObjectParameter("Pvc_Filter4", typeof(string));
    
            var pvc_Filter5Parameter = pvc_Filter5 != null ?
                new ObjectParameter("Pvc_Filter5", pvc_Filter5) :
                new ObjectParameter("Pvc_Filter5", typeof(string));
    
            var pvc_Filter6Parameter = pvc_Filter6 != null ?
                new ObjectParameter("Pvc_Filter6", pvc_Filter6) :
                new ObjectParameter("Pvc_Filter6", typeof(string));
    
            var pvc_TypeParameter = pvc_Type != null ?
                new ObjectParameter("Pvc_Type", pvc_Type) :
                new ObjectParameter("Pvc_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_Txn_RetriveTxnData_Alt_Result>("Usp_Ezy_Txn_RetriveTxnData_Alt", pvc_TxnNumberParameter, pvc_Filter1Parameter, pvc_Filter2Parameter, pvc_Filter3Parameter, pvc_Filter4Parameter, pvc_Filter5Parameter, pvc_Filter6Parameter, pvc_TypeParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_Txn_RetriveTxnData_Alt_Form_Result> Usp_Ezy_Txn_RetriveTxnData_Alt_Form(string pvc_TxnNumber, string pvc_Filter1, string pvc_Filter2, string pvc_Filter3, string pvc_Filter4, string pvc_Filter5, string pvc_Filter6, string pvc_Type)
        {
            var pvc_TxnNumberParameter = pvc_TxnNumber != null ?
                new ObjectParameter("Pvc_TxnNumber", pvc_TxnNumber) :
                new ObjectParameter("Pvc_TxnNumber", typeof(string));
    
            var pvc_Filter1Parameter = pvc_Filter1 != null ?
                new ObjectParameter("Pvc_Filter1", pvc_Filter1) :
                new ObjectParameter("Pvc_Filter1", typeof(string));
    
            var pvc_Filter2Parameter = pvc_Filter2 != null ?
                new ObjectParameter("Pvc_Filter2", pvc_Filter2) :
                new ObjectParameter("Pvc_Filter2", typeof(string));
    
            var pvc_Filter3Parameter = pvc_Filter3 != null ?
                new ObjectParameter("Pvc_Filter3", pvc_Filter3) :
                new ObjectParameter("Pvc_Filter3", typeof(string));
    
            var pvc_Filter4Parameter = pvc_Filter4 != null ?
                new ObjectParameter("Pvc_Filter4", pvc_Filter4) :
                new ObjectParameter("Pvc_Filter4", typeof(string));
    
            var pvc_Filter5Parameter = pvc_Filter5 != null ?
                new ObjectParameter("Pvc_Filter5", pvc_Filter5) :
                new ObjectParameter("Pvc_Filter5", typeof(string));
    
            var pvc_Filter6Parameter = pvc_Filter6 != null ?
                new ObjectParameter("Pvc_Filter6", pvc_Filter6) :
                new ObjectParameter("Pvc_Filter6", typeof(string));
    
            var pvc_TypeParameter = pvc_Type != null ?
                new ObjectParameter("Pvc_Type", pvc_Type) :
                new ObjectParameter("Pvc_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_Txn_RetriveTxnData_Alt_Form_Result>("Usp_Ezy_Txn_RetriveTxnData_Alt_Form", pvc_TxnNumberParameter, pvc_Filter1Parameter, pvc_Filter2Parameter, pvc_Filter3Parameter, pvc_Filter4Parameter, pvc_Filter5Parameter, pvc_Filter6Parameter, pvc_TypeParameter);
        }
    
        public virtual ObjectResult<Usp_Ezy_UpdateAlternativePart_Result> Usp_Ezy_UpdateAlternativePart(string pvc_FolloupNo, string pvc_NewFolloupFLNo, string pvc_NewFolloupSONo)
        {
            var pvc_FolloupNoParameter = pvc_FolloupNo != null ?
                new ObjectParameter("Pvc_FolloupNo", pvc_FolloupNo) :
                new ObjectParameter("Pvc_FolloupNo", typeof(string));
    
            var pvc_NewFolloupFLNoParameter = pvc_NewFolloupFLNo != null ?
                new ObjectParameter("Pvc_NewFolloupFLNo", pvc_NewFolloupFLNo) :
                new ObjectParameter("Pvc_NewFolloupFLNo", typeof(string));
    
            var pvc_NewFolloupSONoParameter = pvc_NewFolloupSONo != null ?
                new ObjectParameter("Pvc_NewFolloupSONo", pvc_NewFolloupSONo) :
                new ObjectParameter("Pvc_NewFolloupSONo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Ezy_UpdateAlternativePart_Result>("Usp_Ezy_UpdateAlternativePart", pvc_FolloupNoParameter, pvc_NewFolloupFLNoParameter, pvc_NewFolloupSONoParameter);
        }
    }
}
