//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBTS.EntityFramework.Transactions
{
    using System;
    
    public partial class Usp_Ezy_Txn_RetriveReference_Result1
    {
        public string ord_followup_no { get; set; }
        public string ord_followup_amdno { get; set; }
        public string ord_followup_stage { get; set; }
        public string ord_followup_ref_id { get; set; }
        public string ord_ref_text { get; set; }
        public Nullable<System.DateTime> ord_ref_date { get; set; }
    }
}
